"""The migration chain runs, and drift is a failure — ticket E0-04.

Acceptance criterion 1: "`alembic upgrade head` succeeds against an empty
database, and `alembic check` reports no drift." Criterion 2: "Deliberately
adding a column to a model without a migration makes `alembic check` fail."

**Why criterion 1 is two tests and neither of them is "it did not raise".** At
this ticket the baseline migration creates nothing, so `alembic check` passes
against a database nobody has touched just as readily as against a correctly
migrated one — an `env.py` that connected and did nothing at all would satisfy
"reports no drift". The upgrade half therefore asserts what the upgrade *left
behind*: the revision the script directory calls head, stamped in
`alembic_version`. That is the one observable difference between a migration
that ran and a migration that was never wired up.

**Why criterion 2 is testable here at all.** The ticket asks for that one by
hand, and rightly: it means editing a model file, and there are no models yet —
E0-04 creates no tables. What can be automated is the property the hand check is
looking for, which is that `alembic check` compares `Base.metadata` against the
live database and fails on a difference. The test below builds that difference
without touching a source file: it declares a table on `Base.metadata` from
inside the test, creates the same table in the database one column short, and
expects `check` to report the missing column. What it does not cover is the
half that only a file edit reaches — that the models `env.py` imports are the
ones a developer edits. Keep the manual check.

**The commands run in this process rather than as a subprocess.** `alembic
check` has to see the test's own additions to `Base.metadata`, and a subprocess
imports its own copy of everything. `alembic.command.upgrade` and
`alembic.command.check` are what the CLI calls, so this is the same code path
with the same configuration file; what it does not exercise is `alembic.ini`
resolving its own `script_location` from `backend/` as `make migrate` does, and
the `migration-drift` job in CI covers that by running the real command line.
"""

from collections.abc import Callable
from typing import Any

import pytest
from alembic import command
from alembic.script import ScriptDirectory
from alembic.util.exc import AutogenerateDiffsDetected
from sqlalchemy import Column, Integer, String, Table, create_engine, text

pytestmark = pytest.mark.integration

# `empty_database` and its siblings hand back the `DatabaseUnderTest` named
# tuple defined in `tests/conftest.py` — `.superuser_url` and
# `.application_url`. It is annotated `Any` here rather than imported: a test
# module importing `conftest` by name works only because of where pytest puts
# `tests/` on `sys.path`, and a collection error is not a failing test.

# A table nothing else will ever declare, so a diff naming it is unambiguously
# this test's doing.
DRIFT_CANARY_TABLE = "e0_04_drift_canary"
DRIFT_CANARY_COLUMN = "added_to_the_model_without_a_migration"

STAMPED_REVISIONS = "SELECT version_num FROM alembic_version"


def load_base() -> Any:
    """Import the declarative `Base` inside the test, so a missing module fails loudly."""
    from app.db import Base

    return Base


def test_upgrade_head_stamps_the_baseline_revision_on_an_empty_database(
    empty_database: Any,
    alembic_config_pointed_at: Callable[[Any], Any],
) -> None:
    """Criterion 1, first half: the chain runs, and it leaves its mark.

    Asserting the stamped revision rather than the absence of an exception is
    deliberate. With no tables in the baseline there is nothing else an upgrade
    changes, so "it did not raise" is satisfied by an `env.py` that opens a
    connection and returns — which is exactly the shape a half-wired migration
    environment has. The revision in `alembic_version` is produced by the
    migration machinery having actually run, and it is compared against the head
    the script directory reports rather than against a literal, because the
    revision identifier is the implementer's to generate.

    It also asserts, in passing, the thing this whole ticket rests on: Alembic
    connected as an identity that may create a table. The application role
    cannot (ADR 0009), so an `env.py` wired to `Settings.database_url` fails
    here with `permission denied for schema public`.
    """
    config = alembic_config_pointed_at(empty_database)

    command.upgrade(config, "head")

    head = ScriptDirectory.from_config(config).get_current_head()
    assert head is not None, (
        "The script directory reports no head revision, so there is no migration chain to "
        "upgrade to. E0-04 ships one baseline migration that creates nothing, establishing "
        "the chain every later schema ticket adds to."
    )

    engine = create_engine(empty_database.superuser_url)
    try:
        with engine.connect() as connection:
            stamped = list(connection.execute(text(STAMPED_REVISIONS)).scalars())
    finally:
        engine.dispose()

    assert stamped == [head], (
        f"After `alembic upgrade head` the database is stamped {stamped!r}, and the script "
        f"directory's head is {head!r}. The two disagree, so either the upgrade did not run "
        "against this database or it stopped short of head."
    )


def test_check_reports_no_drift_after_upgrading_an_empty_database(
    empty_database: Any,
    alembic_config_pointed_at: Callable[[Any], Any],
) -> None:
    """Criterion 1, second half: a freshly migrated database is not drifted.

    Weak on its own and worth keeping anyway. It is the control for the drift
    test below — a `check` that raised whatever it was given would make that one
    pass while proving nothing — and it is the assertion that fails when a
    naming convention or an `include_object` filter makes autogenerate churn
    against a schema it has just created.
    """
    config = alembic_config_pointed_at(empty_database)
    command.upgrade(config, "head")

    command.check(config)


def test_check_fails_when_the_models_carry_a_column_the_database_lacks(
    empty_database: Any,
    alembic_config_pointed_at: Callable[[Any], Any],
) -> None:
    """Criterion 2: a model change with no migration behind it is a failure.

    The mechanism, spelled out because reading it later should not require
    reconstructing it: a table is declared on `Base.metadata` from inside this
    test and created in the database with one of its columns left out, so the
    only difference between the ORM and the schema is that column. If `env.py`
    is wired to `Base.metadata`, `check` sees it.

    **The control runs first, and it is not ceremony.** `check` raising is the
    assertion, and an `env.py` that is broken in any way at all also raises —
    `docs/MISTAKES.md` entry 3, a test passing for a reason unrelated to what it
    asserts. So the same configuration is asked for a clean answer before it is
    asked for a dirty one, and the diffs are inspected rather than counted: the
    failure has to name the column that was added.

    The table is removed from `Base.metadata` afterwards whatever happens.
    `Base` is a module-level object shared by everything in this process, so
    leaving the canary on it would make every later `alembic check` in the
    session fail with this test's name in the message.
    """
    config = alembic_config_pointed_at(empty_database)
    command.upgrade(config, "head")

    command.check(config)  # the control: nothing has drifted yet

    base = load_base()
    canary = Table(
        DRIFT_CANARY_TABLE,
        base.metadata,
        Column("id", Integer, primary_key=True),
        Column(DRIFT_CANARY_COLUMN, String(16)),
    )
    try:
        # The same table, one column short. The primary key is named from the
        # metadata so that the naming convention cannot show up as a second
        # difference and satisfy the assertion below on its own.
        create_one_column_short = (
            f'CREATE TABLE "{DRIFT_CANARY_TABLE}" (id integer NOT NULL,'
            f' CONSTRAINT "{canary.primary_key.name}" PRIMARY KEY (id))'
        )
        engine = create_engine(empty_database.superuser_url)
        try:
            with engine.begin() as connection:
                connection.execute(text(create_one_column_short))
        finally:
            engine.dispose()

        with pytest.raises(AutogenerateDiffsDetected) as drift:
            command.check(config)
    finally:
        base.metadata.remove(canary)

    diffs = list(getattr(drift.value, "diffs", ()))
    assert diffs, (
        "`alembic check` reported drift with no diffs attached, so nothing here says *what* "
        "it objected to. The assertion below cannot tell this apart from the column being "
        "found unless the diffs are read."
    )
    reported = str(diffs)
    assert DRIFT_CANARY_COLUMN in reported, (
        f"`alembic check` failed, but not about the column that was added without a "
        f"migration. It reported: {reported}. A `check` that fails for some other reason is "
        "not the guarantee this ticket turns on — the point is that the *model change* is "
        "what breaks the build."
    )
