"""The tool's own signing key: one row, generated by the seed — E1-05, criterion 4.

E1-06 signs a `client_assertion` with this key and a platform verifies it against
the key set this tool publishes, so the private half has to exist and has to be
the *same* private half in every process that signs: the api container and the
celery worker are two processes and one tool. That is the whole of why custody is
the database rather than a settings variable or a file — per-process generation
and per-container files each give the two processes different keys, and a
platform holding one public key then rejects half the assertions.

Four properties, and each has its own test because each fails differently:

  - **The seed generates one**, and what it generates is a real RSA private key
    of a real size. "A row exists" is satisfied by a row holding an empty string.
  - **The database accepts a second row.** This bullet said the opposite until
    E3-01, and the change is deliberate: E1-05 held the one-row rule in the
    database as `uq_tool_signing_key_one_row`, on the grounds that two rows are
    "two identities for one tool", and E3-01's rotation rule replaces it. A
    rotation needs the retiring key and its replacement published at once, and
    the one-row rule leaves nowhere to put the second; the rule that replaces it
    is that the published set is every row with `retired_at IS NULL` and the
    signer is the newest of those (ADR 0127, amending ADR 0082). The seed still
    writes exactly one key, which is what the first bullet is about; what changed
    is what the *database* permits beside it.
  - **A second run keeps the key it finds.** A seed that rotated the key on every
    run would leave every previously-issued assertion unverifiable and would do
    it silently, since a fresh key signs perfectly well.
  - **The generation is behind ADR 0063's guard**, at the write and not only in
    `main`, exactly as `seed_mock_platform` is (ADR 0068).

**Why the idempotence test plants its own key.** A database only the seed has
written cannot pose the question "does a second run keep what it finds": the rows
it finds and the rows it wrote are the same set by construction, so a seed that
deleted and regenerated the key would produce a fresh key that looks exactly like
a kept one. `docs/MISTAKES.md` entry 31 is that failure, measured on this same
seed script. So the key this test asserts survives is one this test generated,
written to a database of its own before the script has ever run against it.

**Nothing here writes a PEM to a file, and no test in this suite may.** The key
is generated in memory per run, the way SPEC §9.1 requires of every key in this
suite, and the standing sweep that no private key is committed is
`tests/unit/test_mock_lms_service.py::test_no_private_key_material_is_committed_to_the_repository`
— which is criterion 4's grep half, held there rather than copied here so that
one rule has one home (`docs/MISTAKES.md` entry 13). That module's docstring now
names this ticket as its second subject.
"""

from typing import Any

import pytest
from sqlalchemy import select, text

pytestmark = pytest.mark.integration

# The table and the column, spelled by E1-05's work order. One name rather than a
# candidate list: the ticket fixes both, so alternatives here would be this
# module inventing choices the ticket does not leave open.
SIGNING_KEYS = "tool_signing_key"
PRIVATE_KEY_COLUMN = "private_key_pem"

# The object E1-05's one-row rule was held in, kept here because the test below
# names it: an insert refused by *this* index is E3-01's schema change not having
# landed, and a reader who is told the name can check in one query. E3-01 drops
# it (ADR 0127) and `tests/integration/test_the_signing_key_survives_a_downgrade.py`
# is where its return at the revision below is asserted.
ONE_ROW = "uq_tool_signing_key_one_row"

# The floor for the key itself. **Not this module's choice**: E1-05 says RSA
# 2048, and it is also the floor every conformant LTI 1.3 platform will accept
# for an RS256 assertion. Asserted as "at least", so a later ticket that raises
# the size does not have to come back here.
SMALLEST_ACCEPTABLE_KEY_BITS = 2048

# What the PEM armour looks like, assembled rather than written out for the same
# reason `tests/unit/test_mock_lms_service.py` assembles it: the tree-wide sweep
# for committed key material reads every file including this one, and a module
# that is its own offender teaches everybody to add an exclusion.
PEM_PRIVATE_MARKER = "PRIVATE" + " KEY-----"


def require_signing_key_table(tables: dict[str, Any]) -> Any:
    """The declared `tool_signing_key` table, or a failure naming what E1-05 adds.

    Every test here is about the contents of that table, and over a schema
    without it each one would fail somewhere further in — inside a raw statement,
    or inside a fixture's own seeding — which reads as a broken test rather than
    as the missing deliverable it is.
    """
    table = tables.get(SIGNING_KEYS)
    if table is None:
        pytest.fail(
            f"There is no `{SIGNING_KEYS}` table (what is there: {sorted(tables)}). E1-05 adds it "
            "to `backend/app/models/lti.py` with `id` and `private_key_pem`, and the tool's own "
            "signing key lives in it: the api container and the celery worker are two processes "
            "and have to sign with one key, which is what a database column buys and a "
            "per-process or per-container key does not."
        )
    if PRIVATE_KEY_COLUMN not in table.c:
        pytest.fail(
            f"`{SIGNING_KEYS}` has no `{PRIVATE_KEY_COLUMN}` column — it has "
            f"{[column.name for column in table.columns]}. E1-05 stores **only** the private PEM "
            "and derives the public half and the RFC 7638 `kid` on read, because a stored copy of "
            "something derivable is a copy that can drift (`docs/MISTAKES.md` entry 19)."
        )
    return table


def generated_pem() -> str:
    """A fresh RSA private key in PKCS#8 PEM, generated here and never written down.

    SPEC §9.1: keys are generated per test run rather than checked in.
    `cryptography` is already pinned and is what `tests/fixtures/suite_keys.py`
    generates the suite's own signing key with, so this adds no dependency and
    uses the same library the seed itself is asked to use.
    """
    from cryptography.hazmat.primitives import serialization
    from cryptography.hazmat.primitives.asymmetric import rsa

    key = rsa.generate_private_key(public_exponent=65537, key_size=SMALLEST_ACCEPTABLE_KEY_BITS)
    return key.private_bytes(
        encoding=serialization.Encoding.PEM,
        format=serialization.PrivateFormat.PKCS8,
        encryption_algorithm=serialization.NoEncryption(),
    ).decode("ascii")


def loaded_key(pem: Any, where: str) -> Any:
    """`pem` parsed as a private key, or a failure saying what was stored instead.

    Parsed rather than pattern-matched, because "the column holds something that
    begins with a PEM header" is satisfied by armour around anything at all — and
    a key the signing code cannot load is a key that fails at the first client
    assertion, in E1-06, with nothing here having noticed.
    """
    from cryptography.hazmat.primitives import serialization

    assert isinstance(pem, str) and pem.strip(), (
        f"{where} holds {pem!r} rather than a PEM private key. A row with an empty value satisfies "
        "'the seed wrote a key' perfectly and signs nothing."
    )
    try:
        return serialization.load_pem_private_key(pem.encode("ascii"), password=None)
    except (ValueError, TypeError) as refused:
        pytest.fail(
            f"{where} does not parse as an unencrypted PEM private key: {refused}. E1-05 stores "
            "PKCS#8 PEM with no passphrase, because the process that reads it has nowhere to get "
            "one from — an encrypted key here is a key nothing can use."
        )


def signing_key_rows(connection: Any, table: Any) -> list[dict[str, Any]]:
    """Every row of `tool_signing_key`, as mappings."""
    return [dict(row) for row in connection.execute(select(table)).mappings().all()]


def stored_keys(session: Any) -> int:
    """How many signing keys the database holds, counted through raw SQL."""
    query = f"SELECT count(*) FROM public.{SIGNING_KEYS}"  # noqa: S608
    return int(session.execute(text(query)).scalar_one())


def insert_key(session: Any, pem: str) -> None:
    """Write one signing key row, without going through the model."""
    session.execute(
        text(f"INSERT INTO public.{SIGNING_KEYS} ({PRIVATE_KEY_COLUMN}) VALUES (:pem)"),  # noqa: S608
        {"pem": pem},
    )


# ---------------------------------------------------------------------------
# What the seed leaves behind.
# ---------------------------------------------------------------------------


def test_the_seed_leaves_exactly_one_tool_signing_key(
    seeded_demo: Any, demo_database: Any, metadata_tables: dict[str, Any]
) -> None:
    """Criterion 4: the tool key pair exists after a development bring-up.

    **The mutations this kills:** no key generated at all, which is the state at
    HEAD and which nothing else in the suite would notice until E1-06 tries to
    sign; a key generated per process rather than stored, which leaves this table
    empty while a signing test passes inside one interpreter; and a row holding a
    placeholder, which "a row exists" accepts and which fails at the first
    assertion.

    The size is asserted as well as the parse. A 512-bit RSA key loads perfectly,
    signs perfectly, and is refused by every platform that checks — and it is
    what a generation call written for speed produces.
    """
    assert seeded_demo.succeeded, (
        "The seed run this module is built on did not succeed, so an empty "
        f"`{SIGNING_KEYS}` table below would say nothing about what the seed generates.\n"
        f"{seeded_demo.report()}"
    )
    table = require_signing_key_table(metadata_tables)

    with demo_database.connect() as connection:
        rows = signing_key_rows(connection, table)

    assert len(rows) == 1, (
        f"The seed left {len(rows)} rows in `{SIGNING_KEYS}` and E1-05 asks for exactly one. Zero "
        "means the tool has no signing key after a development bring-up, which is the criterion "
        "failing outright. More than one is no longer refused by the database — E3-01 widened the "
        "rule so a rotation has somewhere to put its second key — so this assertion is now the "
        "only thing saying the *seed* writes one: a development bring-up that quietly accumulated "
        "a key per run would be a growing published key set nobody asked for."
    )

    key = loaded_key(rows[0].get(PRIVATE_KEY_COLUMN), f"The seeded `{SIGNING_KEYS}` row")
    assert key.key_size >= SMALLEST_ACCEPTABLE_KEY_BITS, (
        f"The seeded signing key is {key.key_size} bits and E1-05 asks for at least "
        f"{SMALLEST_ACCEPTABLE_KEY_BITS}. A shorter key loads and signs exactly like a long one "
        "and is refused by the platforms that check, which is a failure in E1-06 against a real "
        "LMS and nowhere before it."
    )


def test_the_seed_prints_no_private_key_material(
    seeded_demo: Any, demo_database: Any, metadata_tables: dict[str, Any]
) -> None:
    """The key never reaches a log, an exception message or stdout.

    A seed that reports what it wrote is a good seed, and the natural way to
    report generating a key is to print it. `make seed` runs in a terminal, in
    CI, and inside `docker compose logs`, and SPEC §10 keeps values out of all
    three — a private key printed once is a private key in a scrollback buffer,
    a CI artefact and whatever gets pasted when somebody asks for help.

    **Both halves.** The stored value must not appear, which catches the printed
    key; and no PEM armour of any kind may appear, which catches the *other* key
    somebody printed — a rotation that logged the old one, or a traceback
    quoting the value it failed to parse.

    **The mutation this kills:** any `print(pem)` or `f"generated {pem}"` on the
    seed's success or failure path.
    """
    table = require_signing_key_table(metadata_tables)
    with demo_database.connect() as connection:
        rows = signing_key_rows(connection, table)
    assert rows, (
        f"The seed wrote no `{SIGNING_KEYS}` row, so 'the key is not in the output' is true of a "
        "run that generated no key. The test above owns that failure."
    )

    output = f"{seeded_demo.stdout}\n{seeded_demo.stderr}"
    stored = str(rows[0].get(PRIVATE_KEY_COLUMN) or "")

    assert stored and stored not in output, (
        "The seed printed the private key it generated. Its own output is what a developer reads "
        f"and what CI keeps:\n{output[-2000:]}"
    )
    assert PEM_PRIVATE_MARKER not in output, (
        "The seed's output carries PEM private-key armour, which is either the key it wrote or "
        f"another one it handled on the way past:\n{output[-2000:]}"
    )


# ---------------------------------------------------------------------------
# How many rows the database permits, asked of the database.
# ---------------------------------------------------------------------------


def test_the_first_tool_signing_key_row_is_accepted(
    db_session: Any, metadata_tables: dict[str, Any]
) -> None:
    """One key is the supported state, not zero.

    The control for the test below, and it keeps that job through E3-01's change
    of direction. A schema that refuses *every* insert — a check nothing can
    satisfy, a grant nobody holds, a column that is not there — would make the
    test below red for a reason that has nothing to do with the row-count rule,
    and the two would be indistinguishable without this.
    """
    require_signing_key_table(metadata_tables)
    assert stored_keys(db_session) == 0, (
        f"The migrated database already holds a `{SIGNING_KEYS}` row before this test writes one, "
        "so the counts below cannot be read. Nothing in the session database's fixtures seeds one."
    )

    insert_key(db_session, generated_pem())

    assert stored_keys(db_session) == 1


def test_a_second_tool_signing_key_row_is_accepted(
    db_session: Any, metadata_tables: dict[str, Any]
) -> None:
    """The database has room for a rotation's second key — E3-01, and a reversal.

    **This test asserted the opposite until E3-01, and the change is deliberate.**
    It was `test_a_second_tool_signing_key_row_is_refused`, and it was right: while
    the signing code read *a* row and a platform held the public half of *one* of
    them, a second row was a coin toss on every client assertion. E3-01 replaces
    the read rather than relaxing the rule — the published set is every row with
    `retired_at IS NULL` and the signer is the newest of those by `created_at
    DESC, id DESC` (ADR 0127) — so two rows are two published keys rather than two
    identities, which is precisely what a rotation is. The old assertion is not
    weakened here; it is removed because the fact it rested on is gone, and this
    sentence is the record of that (`docs/MISTAKES.md` entry 1).

    **The mutation this kills:** `uq_tool_signing_key_one_row` left on the table,
    which makes rotation unbuildable — there is nowhere to put the replacement key
    while the retiring one is still published, so every rotation is a gap in which
    assertions signed by the old key verify nowhere.

    **The near misses it must also kill**, and they are why the two keys differ:
    the index moved onto `private_key_pem`, which permits any number of rows
    holding *different* keys and is satisfied by this test; and a partial unique
    index over the unretired rows, which refuses exactly the overlap the rotation
    needs. The second insert here is a second *live* key, so both fail it.

    **Its control is the test above.** A schema that refuses every insert would
    make this red for a reason that is not the row-count rule.
    """
    require_signing_key_table(metadata_tables)
    first, second = generated_pem(), generated_pem()
    assert first != second, "Two generated keys came out identical, so this poses nothing."

    insert_key(db_session, first)
    insert_key(db_session, second)

    assert stored_keys(db_session) == 2, (
        f"A second `{SIGNING_KEYS}` row did not survive. If Postgres refused it and named "
        f"{ONE_ROW}, that is E1-05's one-row index still on the table: E3-01 drops it, because a "
        "rotation needs the retiring key and its replacement published at once and the one-row "
        "rule leaves nowhere to put the second. An index moved onto the key material, or made "
        "partial over the unretired rows, refuses this same pair for the same reason."
    )


# ---------------------------------------------------------------------------
# Idempotence, against a database the seed did not fill.
# ---------------------------------------------------------------------------


def test_the_seed_keeps_a_tool_signing_key_it_finds(
    demo_databases: Any, plant_in: Any, metadata_tables: dict[str, Any]
) -> None:
    """A second bring-up signs with the same key the first one did.

    **The mutation this kills:** a seed that deletes and regenerates, or that
    inserts unconditionally and lets the one-row rule refuse it — the first
    rotates the tool's identity on every `make seed` and the second turns a
    routine re-seed into a crash. Rotation is the dangerous one: a fresh key
    signs perfectly, so nothing fails until a platform that already fetched the
    old public half rejects an assertion, hours later, somewhere else.

    **The key is planted rather than seeded**, which is the whole design of this
    test. Run against a database the seed itself filled, "the key I find" and
    "the key I wrote" are the same value by construction and a regenerating seed
    passes — `docs/MISTAKES.md` entry 31, filed against this same script. So the
    row here is written by this test, into a database at head that the script has
    never run against.
    """
    require_signing_key_table(metadata_tables)
    demo = demo_databases()
    planted = generated_pem()
    plant_in(demo, SIGNING_KEYS, None, **{PRIVATE_KEY_COLUMN: planted})

    run = demo.run()
    assert run.succeeded, (
        "The seed refused to run against a database that already held a tool signing key. An "
        "existing key is the ordinary state of every development database after the first "
        f"`make seed`, so this is a re-seed failing rather than a guard working.\n{run.report()}"
    )

    with demo.connect() as connection:
        rows = signing_key_rows(connection, require_signing_key_table(metadata_tables))

    assert len(rows) == 1, (
        f"After seeding a database that already held one signing key, `{SIGNING_KEYS}` holds "
        f"{len(rows)} rows."
    )
    assert rows[0].get(PRIVATE_KEY_COLUMN) == planted, (
        "The seed replaced the tool signing key it found. E1-05: an existing row is kept, never "
        "rotated. A rotation is invisible at the moment it happens — the new key signs perfectly "
        "— and shows up as a platform rejecting a client assertion signed by a key it has never "
        "seen."
    )


# ---------------------------------------------------------------------------
# The guard, at the write rather than only in `main`.
# ---------------------------------------------------------------------------


def test_the_seed_refuses_to_generate_a_signing_key_outside_a_development_environment(
    seed_module: Any, demo_databases: Any, metadata_tables: dict[str, Any]
) -> None:
    """The key generation sits behind ADR 0063's guard, at the row it writes.

    The twin of
    `tests/integration/test_demo_seed_script.py::test_the_seed_refuses_to_register_the_mock_outside_a_development_environment`,
    and it starts from the same fact: `main` checks the environment before it
    opens a connection, so a subprocess test can only ever observe the script
    exiting non-zero and would go on observing that if the check at this
    particular write were deleted. Reaching past `main` is **necessary** to ask
    whether this write is bound to the guard.

    **It is not sufficient, and the first draft of this test stopped there.** It
    called `seed(session, deployed)`, which is one function further out than
    `main` and still upstream of this write: `seed` calls `seed_mock_platform`
    first, whose own `check_environment_is_development` fires before
    `seed_tool_signing_key` is reached at all. So the `SeedError` it caught and
    the empty table it asserted both came from the **mock platform's** guard, and
    deleting the guard from `seed_tool_signing_key` — or moving it below the write
    — left the test green. The E1-05 mutation battery measured both variants; that
    is `docs/MISTAKES.md` entry 3 in the place its own docstring claimed to have
    closed, which is the way that entry usually arrives.

    **So the refusal is posed at the function itself**, below, and that is the
    half that kills the mutation. The `seed`-level case is kept underneath it as a
    second assertion rather than deleted, because "both guards fire, and the first
    one costs no writes" is a real property of the composition — but it can no
    longer be mistaken for evidence about this write, and its comment says which
    guard it is watching.

    **What a deployment gets from the miss.** A key generated in a production
    database by a script nobody meant to run there is the private half of the
    tool's identity, created outside whatever key management that deployment has,
    by whoever had a development checkout and a production `DATABASE_URL` — the
    residual gap ADR 0063 and ADR 0068 both record and neither closes.

    **The control is at the bottom, on the same database.** A refusal leaves an
    empty table, and an empty table is also what an unmigrated database, a broken
    read or a generation that never writes a key looks like (`docs/MISTAKES.md`
    entry 3). So the same call is made with the same session machinery under the
    development name, and the only thing that differs between it and the refusal
    above it is the environment — one call, one argument, two outcomes.
    """
    from sqlalchemy import create_engine
    from sqlalchemy.orm import Session

    table = require_signing_key_table(metadata_tables)
    generate = getattr(seed_module, "seed_tool_signing_key", None)
    assert callable(generate), (
        "`scripts/seed.py` exposes no `seed_tool_signing_key` (it exposes "
        f"{sorted(name for name in vars(seed_module) if not name.startswith('_'))}). E1-05 puts "
        "the generation there, guarded on `ENVIRONMENT` at the write exactly as "
        "`seed_mock_platform` is, and a test that could not reach it could only ever watch `main` "
        "refuse."
    )

    demo = demo_databases()
    deployed = {
        "ENVIRONMENT": "production",
        "DATABASE_URL": demo.database.superuser_url,
        "DB_SUPERUSER": "unused — the guard refuses before a row is written",
        "DB_SUPERUSER_PASSWORD": "unused — the guard refuses before a row is written",
    }

    engine = create_engine(demo.database.superuser_url)
    try:
        # The refusal, posed at the function that owns the write. Nothing else in
        # the seed runs, so the `SeedError` here can only be this guard and the
        # empty table can only be this guard's doing.
        with Session(bind=engine) as session:
            with pytest.raises(seed_module.SeedError) as refusal:
                generate(session, deployed)
            # Read inside the transaction, before the rollback: a guard moved
            # below the write would leave the row visible here and invisible to
            # any assertion made afterwards. ADR 0068's ordering claim is that a
            # refusal costs no writes at all. A Python exception does not abort
            # the database transaction, so this read is the one that sees such a
            # write.
            written_before_the_refusal = signing_key_rows(session, table)
            session.rollback()

        assert not written_before_the_refusal, (
            f"The refusal came after the write: {len(written_before_the_refusal)} "
            f"`{SIGNING_KEYS}` row(s) were already in the transaction when `seed_tool_signing_key` "
            "raised. Nothing persists, so this is not a hole — it is the ordering ADR 0068 claims, "
            "and a guard that runs after the row it guards is one refactor away from a guard that "
            "does not run at all."
        )
        assert seed_module.ENVIRONMENT_VARIABLE in str(refusal.value), (
            f"`seed_tool_signing_key` refused, and not over the environment: "
            f"{str(refusal.value)!r}. A refusal for another reason would pass this test while "
            "leaving the key generation unguarded."
        )

        with demo.connect() as connection:
            after_the_refusal = signing_key_rows(connection, table)
        assert not after_the_refusal, (
            f"`seed_tool_signing_key` generated a key with {seed_module.ENVIRONMENT_VARIABLE} set "
            "to 'production'."
        )

        # Defence in depth, and **not** evidence about the write above. `seed`
        # calls `seed_mock_platform` first, so the refusal here is whichever guard
        # comes first — today the mock platform's. What it asserts is the
        # composition: a whole-script call under a deployment's environment
        # leaves no key behind, whichever guard stopped it.
        with Session(bind=engine) as session:
            with pytest.raises(seed_module.SeedError):
                seed_module.seed(session, deployed)
            session.rollback()

        with demo.connect() as connection:
            after_the_whole_seed = signing_key_rows(connection, table)
        assert not after_the_whole_seed, (
            f"`seed` left {len(after_the_whole_seed)} `{SIGNING_KEYS}` row(s) behind under "
            f"{seed_module.ENVIRONMENT_VARIABLE}='production'. The refusal above says this write's "
            "own guard holds; this says nothing upstream of it writes a key on the way to being "
            "refused."
        )

        # The control. Everything above is satisfied by an empty table, and this
        # is what says the table was empty because the guard refused rather than
        # because nothing here can write or read a key. One argument differs from
        # the refusal at the top of this test.
        with Session(bind=engine) as session:
            generate(session, {**deployed, "ENVIRONMENT": "development"})
            session.commit()
    finally:
        engine.dispose()

    with demo.connect() as connection:
        control = signing_key_rows(connection, table)

    assert control, (
        "The same call, on the same database, under "
        f"{seed_module.ENVIRONMENT_VARIABLE}='development', generated no key either. So the "
        "refusal above proved nothing: either this database was never migrated, or "
        "`seed_tool_signing_key` does not write a row, and in both cases the assertion this test "
        "exists for was passing over an absence."
    )
    loaded_key(control[0].get(PRIVATE_KEY_COLUMN), "The control row")
