"""The developer test console: the development-only `GET /dev` page.

The console is a convenience for a developer, and nothing a deployment serves. It
lists the web-login people the mock identity provider knows and offers each as a
one-click "sign in as this person" link, plus one launcher link per registered
LTI platform, so both of SPEC §2's entry doors can be walked without typing URLs.
Below those it reports the sections a launch has discovered so far.

**The launcher links come from `lti_platform`** (E1-05). They used to come from
the origin of a process-wide setting, which rendered one link whatever the
database held — including when it held no registration at all, which sent a
developer to a port answering nothing. With nothing registered the page now says
so and how to fix it.

**It is a become-any-user surface, so it is gated exactly the way `/docs` is** —
served only when `ENVIRONMENT` is exactly `development` (ADR 0074), the same value
`app.main` keys the schema and its documentation on. Outside development the
handler answers `404`, indistinguishable from a route that was never registered:
a page enumerating every identity anyone can sign in as is the single worst thing
this feature could hand a production browser. The production refusal is asserted
without a network in `tests/unit/test_dev_console_exposure.py`; the
development-serves direction, with a real roster behind it, in
`tests/integration/test_dev_console.py`.

**A new module, and §13 does not name it** — its `api/` list is the screen
routers plus `deps.py`, and a developer test console is neither a screen nor LTI.
It is a thin router here, and the page it builds lives beside it: a handful of
f-strings, the way `mock-idp/app/pages.py` builds its three pages, because no
template engine is in this project's locked dependency closure.

**The sections table reports sections and never the people in them** (E1-15).
E1 ships no product screen that renders a section's derived calendar, and SPEC
§9.2's exit proof for "a synced section shows correct derived dates" is a browser
proof, so the console grew one row per `section`: the dates and length §2.2's
start letter derives, the modality, how many people are enrolled, and whether a
roster address is stored. **No identity column of any kind** — not a subject, not
a name, not an address, and not the stored roster address itself, which is a
service endpoint carrying the platform's own context identifier. The enrolled
figure is a count and comes from `public.section_enrollment_count`, the view §4.1
invariant 4 puts every count behind. `tests/integration/
test_the_dev_console_names_nobody.py` is the durable assertion of that rule, over
a section a roster sync has really filled.

**Every interpolated value goes through `html.escape` with `quote=True`.** The
subjects and labels come from the mock provider's roster, which is trusted, but
they are escaped anyway — a page that escapes only the values it distrusts is one
audit away from a hole. Nothing a caller or a roster supplies is ever written into
the `<style>` block, which carries no interpolation at all.
"""

from dataclasses import dataclass
from datetime import date
from html import escape
from typing import Any
from urllib.parse import urlencode
from uuid import UUID

import httpx
from fastapi import APIRouter, Depends, HTTPException, Request
from fastapi.responses import HTMLResponse
from sqlalchemy import select, text
from sqlalchemy.orm import Session

from app.api.auth import LOGIN_PATH
from app.config import Settings, is_development
from app.db import get_session
from app.lti.registration import launcher_origins
from app.models.org import Course, Prefix, Section

router = APIRouter(tags=["dev"])

DEV_CONSOLE_PATH = "/dev"

# Where the console reads the roster from. The mock provider publishes its
# registration and its seed together (ADR 0058) under this path on the issuer's
# host, and the fetch goes through `app.state.http` — the one client every
# server-side call the tool makes already shares.
MOCK_REGISTRATION_PATH = "/mock/registration"

# How long the console waits for the roster. The page is a development
# convenience, so a slow mock should make it say so rather than hang.
ROSTER_TIMEOUT_SECONDS = 5.0

NOT_FOUND = 404

CONSOLE_TITLE = "Pulse Surveys — developer test console"

# The sections table's `data-testid` vocabulary, spelled once. E1-15's browser
# specs address these and nothing else on the table, so a rename is one edit here
# and one in `tests/e2e/`.
#
# A row is keyed by what a person writes on a timetable — `dev-section-BIOL-215-R3WW`
# — rather than by the section's primary key, because a `uuid` is regenerated by
# every reseed and a spec cannot name one. Two sections could in principle share
# a prefix, a number and a code across two terms, and would then share a row key;
# the development stack seeds one term, and the alternative — hanging a term on
# the key — would make every spec spell a term it has nothing to say about.
SECTION_ROW_TESTID_PREFIX = "dev-section-"
SECTION_START_DATE_TESTID = "section-start-date"
SECTION_END_DATE_TESTID = "section-end-date"
SECTION_LENGTH_WEEKS_TESTID = "section-length-weeks"
SECTION_MODALITY_TESTID = "section-modality"
SECTION_ENROLLED_COUNT_TESTID = "section-enrolled-count"
SECTION_ROSTER_ADDRESS_TESTID = "section-roster-address-stored"

# What the roster-address cell says. A yes or a no on
# `lms_context_memberships_url IS NOT NULL` (SPEC §7.3's never-synced state), and
# never the address: it carries the platform's own context identifier and is the
# target of a credentialled service call.
ADDRESS_STORED = "yes"
ADDRESS_NOT_STORED = "no"

# How many people each section holds, read from the view rather than counted off
# `public.enrollment`. SPEC §4.1 invariant 4 — "aggregate language counts
# sections, never instructors" — puts every count behind
# `public.section_enrollment_count`, whose own SQL says why: a count is the shape
# most likely to be extended with "…and their names", and this is the read path
# that cannot be.
#
# Spelled here rather than reached through `app.views_sql.queries`, which
# `tests/unit/test_the_org_views_are_read_only_through_the_grant.py` keeps to the
# single importer that is the authorization chokepoint — this console asks a
# question with no actor and no purview in it, and importing that module would
# turn a one-importer rule into a two-importer one. Its helper takes a course in
# any case; the console lists every section there is.
_SECTION_ENROLLED_COUNTS = text(
    "SELECT section_id, enrolled_count FROM public.section_enrollment_count"
)


@dataclass(frozen=True, slots=True)
class ConsoleSection:
    """One row of the sections table: a section's calendar, a count, and a yes/no.

    Nothing on it names a person. The count is an integer and the roster address
    is reduced to whether there is one before it ever leaves the database.
    """

    prefix: str
    number: str
    code: str
    start_date: date
    end_date: date
    length_weeks: int
    modality: str
    enrolled_count: int
    roster_address_stored: bool

    @property
    def testid(self) -> str:
        """`dev-section-BIOL-215-R3WW` — the row key the browser specs address."""
        return f"{SECTION_ROW_TESTID_PREFIX}{self.prefix}-{self.number}-{self.code}"

    @property
    def label(self) -> str:
        """The section as a person writes it (SPEC §2.2, §8)."""
        return f"{self.prefix} {self.number} {self.code}"


# Static CSS, no interpolation: this is code, never a value a caller or a roster
# supplied, so it does not go through `escape` and nothing from a request is ever
# written into it. A cool teal accent, distinct from the mock IdP's violet and the
# mock platform's slate, so the three test surfaces are never mistaken for one
# another, and from Pulse's own palette (`design/tokens.css` is deliberately not
# referenced — this is a developer scaffold, not a product screen).
STYLE = """
    :root { color-scheme: light dark; }
    * { box-sizing: border-box; }
    body {
      margin: 0;
      min-height: 100vh;
      display: flex;
      justify-content: center;
      padding: 2.5rem 1rem;
      font-family: system-ui, -apple-system, "Segoe UI", Roboto, sans-serif;
      background: #f0faf9;
      color: #18181b;
    }
    .card {
      width: 100%;
      max-width: 640px;
      background: #ffffff;
      border-radius: 12px;
      box-shadow: 0 1px 3px rgba(0, 0, 0, 0.08), 0 8px 24px rgba(0, 0, 0, 0.06);
      padding: 2rem 2.25rem 2.25rem;
      height: fit-content;
    }
    h1 { font-size: 1.375rem; margin: 0 0 0.5rem; color: #0f766e; }
    h2 {
      font-size: 1rem;
      margin: 2rem 0 0.75rem;
      color: #0f766e;
      border-top: 1px solid #e5e7eb;
      padding-top: 1.25rem;
    }
    p { line-height: 1.5; color: #3f3f46; margin: 0.5rem 0 1rem; }
    .banner {
      display: flex;
      gap: 0.6rem;
      align-items: flex-start;
      background: #fff7ed;
      border: 1px solid #fdba74;
      color: #9a3412;
      padding: 0.75rem 1rem;
      border-radius: 8px;
      font-size: 0.875rem;
      line-height: 1.4;
      margin-bottom: 1.5rem;
    }
    .banner strong { font-weight: 600; }
    .note {
      background: #fef2f2;
      border: 1px solid #fca5a5;
      color: #991b1b;
      padding: 0.75rem 1rem;
      border-radius: 8px;
      font-size: 0.875rem;
      line-height: 1.4;
    }
    ul { list-style: none; margin: 0; padding: 0; }
    li { margin: 0.4rem 0; }
    a.action {
      display: inline-block;
      color: #0f766e;
      font-weight: 600;
      text-decoration: none;
      padding: 0.15rem 0;
    }
    a.action:hover { text-decoration: underline; }
    code {
      font-family: ui-monospace, SFMono-Regular, Menlo, Consolas, monospace;
      font-size: 0.85em;
      background: rgba(0, 0, 0, 0.05);
      padding: 0.1em 0.35em;
      border-radius: 4px;
      color: #52525b;
    }
    .scroller { overflow-x: auto; }
    table { border-collapse: collapse; width: 100%; font-size: 0.8125rem; }
    th, td { text-align: left; padding: 0.35rem 0.6rem; white-space: nowrap; }
    thead th { color: #52525b; border-bottom: 1px solid #e5e7eb; font-weight: 600; }
    tbody th { font-weight: 600; }
    tbody tr + tr th, tbody tr + tr td { border-top: 1px solid #f4f4f5; }
    @media (prefers-color-scheme: dark) {
      body { background: #0c1a19; color: #e4e4e7; }
      .card { background: #18181b; box-shadow: 0 1px 3px rgba(0, 0, 0, 0.4); }
      h1, h2 { color: #5eead4; }
      h2 { border-top-color: #3f3f46; }
      p { color: #a1a1aa; }
      a.action { color: #5eead4; }
      code { background: rgba(255, 255, 255, 0.08); color: #a1a1aa; }
      .banner { background: #451a03; border-color: #c2410c; color: #fed7aa; }
      .note { background: #450a0a; border-color: #b91c1c; color: #fecaca; }
      thead th { color: #a1a1aa; border-bottom-color: #3f3f46; }
      tbody tr + tr th, tbody tr + tr td { border-top-color: #27272a; }
    }
"""

# Static banner markup, no interpolation.
BANNER = """
    <div class="banner">
      <span>&#9888;&#65039;</span>
      <span>
        <strong>Development-only test console.</strong>
        It offers one-click sign-in as any web-login identity and a launch into the
        mock LMS. It is served only in development and never in a deployment.
      </span>
    </div>"""


def page(body: str) -> str:
    """The shell the console renders inside, so its markup has one shape."""
    return f"""<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>{escape(CONSOLE_TITLE)}</title>
    <style>{STYLE}</style>
  </head>
  <body>
    <div class="card">
      {BANNER}
{body}
    </div>
  </body>
</html>
"""


def sign_in_link(subject: str, label: str) -> str:
    """A "sign in as this person" link to the web door, carrying `login_hint`.

    The subject rides as OIDC Core 1.0 §3.1.2.1's `login_hint`, which the tool
    forwards to the provider so its form pre-selects this person. `target="_blank"`
    so a click opens the flow in a new tab and the console stays put — a developer
    signs in, then comes back to pick the next identity.
    """
    href = f"{LOGIN_PATH}?{urlencode({'login_hint': subject})}"
    return (
        f'<li><a class="action" href="{escape(href, quote=True)}" target="_blank">'
        f"Sign in as {escape(label)}</a> "
        f"<code>{escape(subject)}</code></li>"
    )


def web_section(users: list[dict[str, Any]]) -> str:
    """The web-login roster, one sign-in link per person the provider publishes."""
    people = [user for user in users if user.get("web_login") and user.get("sub")]
    links = "\n          ".join(
        sign_in_link(str(user["sub"]), str(user.get("label") or user["sub"])) for user in people
    )
    return f"""    <h2>Web login</h2>
    <p>Sign in through the identity provider (SPEC §2) as any seeded person.</p>
    <ul>
          {links}
    </ul>"""


def unreachable_section() -> str:
    """What the web section becomes when the roster cannot be fetched."""
    return """    <h2>Web login</h2>
    <p class="note">
      The mock identity provider is unreachable, so the web-login roster could not
      be loaded. Bring it up and reload this page.
    </p>"""


def launcher_section(origins: list[str]) -> str:
    """One launcher link per registered platform origin, or an honest line saying none is.

    **The empty case is a case, not a blank space.** While the origin came from a
    process-wide setting there was always a link, including on a database that
    had never been seeded — which sent a developer to a port answering nothing
    and read as a broken stack. The console reads the registrations now, so the
    absence is visible, and the honest answer to it names what is missing and how
    to fix it.
    """
    if not origins:
        return """    <h2>LTI launch</h2>
    <p class="note">
      No LTI platform is registered, so there is nothing to launch from. Run
      <code>make seed</code> to register the mock LMS, then reload this page.
    </p>"""
    links = "\n          ".join(
        f'<li><a class="action" href="{escape(origin, quote=True)}" target="_blank">'
        f"Open the launcher at {escape(origin)}</a></li>"
        for origin in origins
    )
    return f"""    <h2>LTI launch</h2>
    <p>Launch as an instructor or a student from a registered platform (SPEC §2).</p>
    <ul>
          {links}
    </ul>"""


def roster_users(settings: Settings, http: httpx.Client) -> list[dict[str, Any]] | None:
    """The provider's published users, or `None` when the roster cannot be fetched.

    `None` is the console's fail-soft signal, not a raised error: a page that says
    "the mock is down" is better than one that answers `500` because a development
    dependency is not running. Every failure to obtain a well-formed list of user
    records collapses to it.
    """
    url = f"{settings.oidc_issuer.rstrip('/')}{MOCK_REGISTRATION_PATH}"
    try:
        answered = http.get(url, timeout=ROSTER_TIMEOUT_SECONDS)
    except httpx.HTTPError:
        return None
    if answered.status_code != 200:
        return None
    try:
        document = answered.json()
    except ValueError:
        return None
    if not isinstance(document, dict):
        return None
    users = document.get("users")
    if not isinstance(users, list):
        return None
    return [user for user in users if isinstance(user, dict)]


def console_sections(session: Session) -> list[ConsoleSection]:
    """Every section, with its derived calendar and how many people are in it.

    Two statements rather than one join, because the count comes from a view and
    the calendar comes from the base tables, and joining a view into an ORM select
    would mean spelling the view's column list twice. The count defaults to zero
    for a section the view has no row for, which cannot happen — it is a
    `LEFT JOIN` over `section` — and is written anyway so that a section is never
    dropped from the page by a missing count.

    Ordered the way a person reads a timetable, so the table is stable between
    reloads and a spec polling it sees the same row in the same place.
    """
    counted: dict[UUID, int] = {
        row.section_id: row.enrolled_count for row in session.execute(_SECTION_ENROLLED_COUNTS)
    }
    rows = session.execute(
        select(
            Section.id,
            Prefix.code,
            Course.lms_number,
            Section.lms_section_code,
            Section.start_date,
            Section.end_date,
            Section.length_weeks,
            Section.modality,
            # Reduced to a boolean **in the database**, so the address itself is
            # never selected onto this page's connection at all.
            Section.lms_context_memberships_url.is_not(None),
        )
        .join(Course, Course.id == Section.course_id)
        .join(Prefix, Prefix.id == Course.prefix_id)
        .order_by(Prefix.code, Course.lms_number, Section.lms_section_code)
    )
    return [
        ConsoleSection(
            prefix=prefix,
            number=number,
            code=code,
            start_date=start_date,
            end_date=end_date,
            length_weeks=length_weeks,
            # The member's name — `ONLINE`, `FACE_TO_FACE` — which is also its
            # value (`app.models.org.Modality`), so the page and the column say
            # the same word.
            modality=modality.name,
            enrolled_count=counted.get(section_id, 0),
            roster_address_stored=stored,
        )
        for (
            section_id,
            prefix,
            number,
            code,
            start_date,
            end_date,
            length_weeks,
            modality,
            stored,
        ) in rows
    ]


def section_row(section: ConsoleSection) -> str:
    """One `<tr>`: the section, its calendar, its count and whether it can be synced."""

    def cell(testid: str, value: str) -> str:
        return f'<td data-testid="{escape(testid, quote=True)}">{escape(value)}</td>'

    return (
        f'<tr data-testid="{escape(section.testid, quote=True)}">'
        f'<th scope="row">{escape(section.label)}</th>'
        f"{cell(SECTION_START_DATE_TESTID, section.start_date.isoformat())}"
        f"{cell(SECTION_END_DATE_TESTID, section.end_date.isoformat())}"
        f"{cell(SECTION_LENGTH_WEEKS_TESTID, str(section.length_weeks))}"
        f"{cell(SECTION_MODALITY_TESTID, section.modality)}"
        f"{cell(SECTION_ENROLLED_COUNT_TESTID, str(section.enrolled_count))}"
        f"{cell(
            SECTION_ROSTER_ADDRESS_TESTID,
            ADDRESS_STORED if section.roster_address_stored else ADDRESS_NOT_STORED,
        )}"
        "</tr>"
    )


def sections_section(sections: list[ConsoleSection]) -> str:
    """The sections table, or an honest line saying nothing has been discovered yet.

    **The empty case is a case**, for the reason `launcher_section` gives about
    its own: a blank space reads as a broken page, and "no section exists yet" is
    a state SPEC §7.3 makes ordinary — a section is discovered by a staff launch
    and by nothing else, so a freshly migrated database has none.
    """
    if not sections:
        return """    <h2>Sections</h2>
    <p class="note">
      No section has been discovered yet. A section is created by a staff launch
      (SPEC §7.3), so launch as an instructor from the mock LMS and reload this
      page.
    </p>"""
    rows = "\n          ".join(section_row(section) for section in sections)
    return f"""    <h2>Sections</h2>
    <p>
      What each section's code derives to (SPEC §2.2), how many people the last
      roster sync enrolled, and whether a roster address is stored to sync from
      (SPEC §7.3). Sections only — never the people in them.
    </p>
    <div class="scroller">
    <table>
      <thead>
        <tr>
          <th scope="col">Section</th>
          <th scope="col">Starts</th>
          <th scope="col">Ends</th>
          <th scope="col">Weeks</th>
          <th scope="col">Modality</th>
          <th scope="col">Enrolled</th>
          <th scope="col">Roster address</th>
        </tr>
      </thead>
      <tbody>
          {rows}
      </tbody>
    </table>
    </div>"""


@router.get(DEV_CONSOLE_PATH, summary="Development-only test console for both entry doors")
def dev_console(request: Request, session: Session = Depends(get_session)) -> HTMLResponse:
    """Render the console, or `404` outside development.

    The gate is the whole safety of the feature (see the module docstring), and it
    is checked here so production is indistinguishable from a route that was never
    registered. Synchronous, and the blocking things it does — the roster fetch
    over the network, and two reads for the sections table — run in FastAPI's
    threadpool the way `app.api.auth.begin_web_login` does.

    **The session is taken before the gate rather than after**, because
    `Depends` resolves before the handler body runs either way. It costs a
    connection from the pool on a request a deployment answers `404` to, which is
    the same cost every other routed dependency has and is why the gate stays in
    the handler (ADR 0079) rather than moving anywhere clever.
    """
    settings: Settings = request.app.state.settings
    if not is_development(settings):
        raise HTTPException(status_code=NOT_FOUND)

    users = roster_users(settings, request.app.state.http)
    web = unreachable_section() if users is None else web_section(users)
    body = f"""    <h1>{escape(CONSOLE_TITLE)}</h1>
    <p>Walk either of Pulse's two entry doors (SPEC §2) without typing URLs.</p>
{web}
{launcher_section(launcher_origins(session))}
{sections_section(console_sections(session))}"""
    return HTMLResponse(page(body))
