"""the registration owns its endpoints and the tool owns its key

Revision ID: 34bf86adb774
Revises: 023a8093eb65
Create Date: 2026-08-25 10:14:10.488038

E1-05. Three objects, and each carries a decision worth reading before it is
changed; `backend/app/models/lti.py` holds the full reasoning beside the
columns.

**`lti_platform.authorization_endpoint` and `lti_platform.auth_token_url` are
nullable, deliberately.** E0-23 left the platform's service addresses to E1, so
every registration written before this revision has no value for either — a
`NOT NULL` column would have needed a backfill this migration would have had to
invent, and an invented address is a record asserting something untrue. NULL
means "not stated": the seed's idempotent re-run fills the authorization
endpoint on the rows that predate it, and a launch from a registration that
still states none is refused rather than defaulted (`app.lti.launch`).

**`tool_signing_key` holds one row and the tool's one identity.** The one-row
rule is a unique index on a constant expression, the shape ADR 0072 chose for
`institution` and for the reason it gives: a check constraint sees one row at a
time and cannot count its own table. The index is on `(true)` and emphatically
not on `private_key_pem` — unique key material would permit any number of rows
holding *different* keys, which is the state this exists to refuse. `alembic
check` compares an expression index in both directions (measured on E0-22
against `uq_institution_one_row`), so the drift gate covers this object and no
catalog assertion has to.

**No `pulse_app` grant is issued on `tool_signing_key` here, and that is the
decision rather than the omission.** Nothing reads the key until E1-06 signs
with it; the grant lands there, in the change that spends it, so a runtime role
never holds read access to a private key it never opens. The §4.1 grant
equality compares privileges *held*, so a table granted nothing contributes no
entry to it.

Autogenerated, then documented. The index name is spelled out rather than built
by `op.f(...)`: the `ix` template on `Base.metadata` interpolates a column name
and a textual expression has none to give it, so the model names this index
explicitly too and the two spellings have to match.
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "34bf86adb774"
down_revision: str | Sequence[str] | None = "023a8093eb65"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply this revision."""
    op.create_table(
        "tool_signing_key",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("private_key_pem", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tool_signing_key")),
    )
    op.create_index(
        "uq_tool_signing_key_one_row", "tool_signing_key", [sa.literal_column("(true)")], unique=True
    )
    op.add_column("lti_platform", sa.Column("authorization_endpoint", sa.Text(), nullable=True))
    op.add_column("lti_platform", sa.Column("auth_token_url", sa.Text(), nullable=True))


def downgrade() -> None:
    """Undo this revision."""
    op.drop_column("lti_platform", "auth_token_url")
    op.drop_column("lti_platform", "authorization_endpoint")
    op.drop_index("uq_tool_signing_key_one_row", table_name="tool_signing_key")
    op.drop_table("tool_signing_key")
