"""classification table

Revision ID: 7b41d2c9e6af
Revises: 9a71c4be0d3f
Create Date: 2026-08-17 21:05:00.000000

SPEC §8's `classification` table (E0-13): one row per model verdict, carrying the
prompt version and the model ID that produced it, append-only. Autogenerated from
`app.models.ai` and then edited for three things, each noted where it appears —
the check constraint's expression is written out rather than left as one escaped
line, the downgrade drops the `classification_task` enum type, which autogenerate
does not emit, and the grants at the end are a file this revision executes.

Every constraint name comes from `op.f(...)`, which is the naming convention on
`Base.metadata` rendering it. None is hand-written; see `app/models/base.py`.

**The grants are the append-only instrument.** `classification_grants_v001.sql`
gives `pulse_app` `SELECT` and `INSERT` on this table and nothing else, so the
connection the API and the Celery worker hold cannot rewrite a verdict whatever
the application asks it to. E0-13 is the first ticket in which application code
writes application data, so it is also the first that needs a privilege on a
table rather than on a read view (ADR 0055).

**What `alembic check` compares here, and what it does not.** The columns and the
primary key, yes. The check constraint's *name*, on the pinned Alembic 1.19 —
E0-08's revision measured that and its docstring records it — but not its
expression, and no grant at all. So a change to the verdict vocabulary in
`app/ai/contracts.py` moves `VALIDITY_VERDICT_TOKENS` in `app/models/ai.py` and
the check constraint with it, and this revision keeps applying what it applied on
the day it ran until a later revision replaces the constraint.
`tests/integration/test_ai_gateway_validity_roundtrip.py` is what notices the
grant, over a `pulse_app` connection, for the reason E0-10 and E0-11 both give:
a missing grant should fail as a test rather than as a production incident.
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

from app.views_sql import read_sql

# revision identifiers, used by Alembic.
revision: str = "7b41d2c9e6af"
down_revision: str | Sequence[str] | None = "9a71c4be0d3f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# `classified_at` is declared in the model as `AwareDateTime`, a `TypeDecorator`
# that refuses a naive value at the bind boundary (ADR 0019). That guard is a
# property of the application's write path and not of the schema: the DDL it
# emits is exactly this. Written out rather than imported for the reason E0-06's
# revision gives — a migration records what was applied on the day it ran, and
# importing an application class would make this revision change meaning whenever
# that class did. `alembic check` compares the compiled type, so the two stay in
# step.
TIMESTAMP = sa.DateTime(timezone=True)

# Bound to a name for the same reason E0-10's revision binds `audit_action`: the
# type is created as a side effect of the column below, and the downgrade needs
# an object to call `.drop()` on, since `op.drop_table` leaves the type behind.
CLASSIFICATION_TASK = sa.Enum("COMMENT_VALIDITY", name="classification_task")

# A verdict is only meaningful inside its task's closed set, and two of §7.4's
# five tasks produce verdicts whose sets overlap without agreeing — `nonsense` is
# a comment-validity verdict and a moderation verdict both. Written out here as
# it stood when this revision was applied; `app/models/ai.py` builds the same
# expression from `ValidityVerdict`, so the vocabulary has one source going
# forward and `alembic check` compares the name that carries it.
VERDICT_VOCABULARY = (
    "task <> 'COMMENT_VALIDITY'"
    " OR verdict IN ('substantive', 'insufficient', 'nonsense')"
)

# The scripts this revision runs. Written out rather than globbed, for the reason
# E0-10's revision gives: a directory listing is not a dependency order, and a
# file added to the directory does nothing until a revision names it.
SCRIPTS = ("classification_grants_v001",)


def upgrade() -> None:
    """Apply this revision."""
    op.create_table(
        "classification",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("classified_at", TIMESTAMP, server_default=sa.text("now()"), nullable=False),
        sa.Column("task", CLASSIFICATION_TASK, nullable=False),
        sa.Column("verdict", sa.Text(), nullable=False),
        sa.Column("prompt_version", sa.Text(), nullable=False),
        sa.Column("model_id", sa.Text(), nullable=False),
        sa.CheckConstraint(
            VERDICT_VOCABULARY,
            name=op.f("ck_classification_verdict_is_in_its_tasks_vocabulary"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_classification")),
    )

    for script in SCRIPTS:
        op.execute(read_sql(script))


def downgrade() -> None:
    """Undo this revision.

    The grants need no revoke: they are on the table this drops, and a privilege
    cannot outlive the object it is on. The enum type does need dropping —
    `op.drop_table` leaves it behind, and a second `upgrade()` would then fail on
    a type that already exists.
    """
    op.drop_table("classification")
    CLASSIFICATION_TASK.drop(op.get_bind())
