"""section derived columns

Revision ID: e046c1b23e54
Revises: 216896354431
Create Date: 2026-08-15 17:42:32.129795

The four columns a section's code derives to — `length_weeks`, `start_date`,
`end_date` and `modality` (SPEC §2.2, §8, E0-07) — and the one change to
E0-06's start-letter map that reading §2.2's whole seed map needs.

Autogenerated from `app.models.org` and `app.models.term`, then changed in one
way that alters what it does, noted where it appears: the downgrade drops the
`modality` enum type, which autogenerate does not emit. The rest is formatting,
to match the revisions E0-05 and E0-06 wrote.

**The four columns are added NOT NULL with no backfill**, which is correct only
because no deployment has section rows yet — sections arrive with the roster
sync in E1 and the seed script in E0-17, both later than this. There is no value
this revision could invent for an existing row: a section's calendar is derived
from its code against its term's map, and this revision has no term in hand. If
this ever has to run against a populated table, the fix is a data migration that
calls `app.services.section_codes.apply_section_code` per row, not a nullable
column. That is the same argument E0-06's revision makes for `section.term_id`,
and it is the same table.

**The start-letter map check is widened from `^[A-Z]$` to `^[A-Z0-9]$`.** SPEC
§2.2 numbers the 3-week sections 2 through 7 while every other length is
lettered, so six of the twenty start positions in the Fall 2026 seed map are
digits and E0-06's constraint refuses all six. The constraint is renamed with
the widening rather than edited under its old name: it was called
`letter_is_one_upper_case_letter`, which the new expression makes untrue, and a
name that lies about its own constraint is the shape of `docs/MISTAKES.md`
entry 1.

Every constraint name comes from `op.f(...)`, which is the naming convention on
`Base.metadata` rendering it. None is hand-written; see `app/models/base.py`.
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e046c1b23e54"
down_revision: str | Sequence[str] | None = "216896354431"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# SPEC §2.2's two modalities, as the Postgres enum type that holds them. Named
# for the meanings and not for the `WW`/`FF` suffixes a code spells them with —
# the suffixes are read by `app.services.section_codes` and go no further.
# Written out here rather than imported from `app.models.org` for the reason
# E0-05's revision gives for the course-level expression: a migration records
# what was applied on the day it ran, and importing an application class would
# make this revision change meaning whenever that class did.
MODALITY = sa.Enum("ONLINE", "FACE_TO_FACE", name="modality")


def upgrade() -> None:
    """Apply this revision."""
    op.add_column("section", sa.Column("length_weeks", sa.Integer(), nullable=False))
    op.add_column("section", sa.Column("start_date", sa.Date(), nullable=False))
    op.add_column("section", sa.Column("end_date", sa.Date(), nullable=False))
    # `CREATE TYPE` is emitted here rather than left to the column. A `sa.Enum`
    # creates its type as part of `CREATE TABLE`, and E0-05's revision relies on
    # that; `ALTER TABLE ... ADD COLUMN` emits no such hook, so the column
    # arrives referring to a type that does not exist and the revision fails
    # with "type modality does not exist". Measured — the first version of this
    # file did exactly that.
    MODALITY.create(op.get_bind(), checkfirst=False)
    op.add_column("section", sa.Column("modality", MODALITY, nullable=False))
    op.drop_constraint(
        op.f("ck_start_letter_map_letter_is_one_upper_case_letter"),
        "start_letter_map",
        type_="check",
    )
    op.create_check_constraint(
        op.f("ck_start_letter_map_letter_is_one_start_position"),
        "start_letter_map",
        "letter ~ '^[A-Z0-9]$'",
    )


def downgrade() -> None:
    """Undo this revision."""
    op.drop_constraint(
        op.f("ck_start_letter_map_letter_is_one_start_position"),
        "start_letter_map",
        type_="check",
    )
    op.create_check_constraint(
        op.f("ck_start_letter_map_letter_is_one_upper_case_letter"),
        "start_letter_map",
        "letter::text ~ '^[A-Z]$'::text",
    )
    op.drop_column("section", "modality")
    op.drop_column("section", "end_date")
    op.drop_column("section", "start_date")
    op.drop_column("section", "length_weeks")
    # Autogenerate does not emit this. `CREATE TYPE` rode in with the `modality`
    # column above, so without the matching drop the type outlives the column
    # that used it and the next upgrade fails with "type modality already
    # exists" — a downgrade that cannot be undone. E0-05's revision drops
    # `course_level` for the same reason.
    MODALITY.drop(op.get_bind())
