"""identity separated read views

Revision ID: 446183e8cc5f
Revises: 014ccb3d0fe5
Create Date: 2026-08-16 22:04:54.145312

E0-10: the two runtime database roles, the first two identity-separated read
views, the `SECURITY DEFINER` reveal function that is Care's only route to a
name, the grants that make all of that true, and the `audit_log` table the
reveal writes into (SPEC §4, §4.1, §8; ADR 0001, ADR 0009).

Autogenerated for `audit_log` alone and then changed in three ways:

  - the downgrade drops the `audit_action` enum type, which autogenerate does not
    emit — the same edit E0-05, E0-06 and E0-09's revisions each made;
  - the five `views_sql/` scripts are executed by hand, because no role, view,
    function or grant is visible to autogenerate in either direction;
  - the rest is reformatting, to match the revisions before it.

**The SQL is read from `backend/app/views_sql/` rather than written out here,
and that is a deliberate exception to this tree's own rule.** Every other
revision writes its DDL out verbatim, for the reason E0-05's gives: a migration
records what was applied on the day it ran, and importing an application class
would make the revision change meaning whenever that class did. That objection
applies to a file read at upgrade time with full force, and it is answered rather
than ignored: a `views_sql/` file carries a version in its name and is never
edited once a revision executes it, so the text this revision runs is fixed by
the file name (ADR 0041, following ADR 0032 for prompts). What is bought is the
thing that cannot be had otherwise — Postgres keeps no record of the text a
`CREATE VIEW` was written with, only a parse tree of oids, so a view whose SQL
lives inside a revision string is a view whose schema-qualification nothing can
check. `tests/integration/test_identity_separated_views.py` sweeps those files
and asserts every view in the database is named in one of them.

**Order is stated rather than globbed.** The roles must exist before anything is
granted to them, the views and the function before the grants that name them, and
a directory listing is not a dependency order. A new file added here does nothing
until a revision names it, which is the safe direction.

**What `alembic check` can and cannot see in this revision.** It compares
`audit_log` and its two indexes. It reads neither `pg_roles`, `pg_class` for
views, nor `pg_proc`, so dropping the reveal function, dropping a view, or
granting `SELECT ON user_identity TO pulse_app` all leave the check green. The
tests in `tests/integration/test_identity_grants.py` and
`tests/integration/test_identity_separated_views.py` are the only thing that
notices, and three of them are `invariant`-marked so a skip is a build failure.
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

from app.views_sql import read_sql

# revision identifiers, used by Alembic.
revision: str = "446183e8cc5f"
down_revision: str | Sequence[str] | None = "014ccb3d0fe5"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# `occurred_at` is declared in the model as `AwareDateTime`, a `TypeDecorator`
# that refuses a naive value at the bind boundary (ADR 0019). That guard belongs
# to the application's write path and not to the schema: the DDL it emits is
# exactly this. Written out here for the same reason E0-06's revision gives.
TIMESTAMP = sa.DateTime(timezone=True)

# The enum type `audit_log.action` is declared with. Named here because the
# downgrade needs an object to call `.drop()` on — `op.drop_table` does not
# remove the type that rode in with the column.
AUDIT_ACTION = sa.Enum("IDENTITY_REVEAL", name="audit_action")

# The scripts this revision runs, in the order it runs them. Roles first, because
# nothing can be granted to a role that does not exist; the two views and the
# function next, because the grants name them; the grants last.
SCRIPTS = (
    "identity_roles_v001",
    "section_roster_v001",
    "section_enrollment_count_v001",
    "reveal_student_identity_v001",
    "identity_grants_v001",
)

# What the downgrade removes, and what it deliberately leaves. The views and the
# function go, and their grants go with them, because a privilege cannot outlive
# the object it is on. **The two roles stay.** On any Compose volume `pulse_app`
# was created by `scripts/db-init` before this revision ever ran (ADR 0009), so
# dropping it here would remove something this revision did not create and would
# take the running application's login with it. `DROP ROLE` would also fail
# against any object elsewhere in the cluster that depends on it, which is a
# confusing way for a downgrade to stop halfway.
DROP_OBJECTS = (
    "DROP FUNCTION IF EXISTS public.reveal_student_identity(uuid, uuid, uuid)",
    "DROP VIEW IF EXISTS public.section_enrollment_count",
    "DROP VIEW IF EXISTS public.section_roster",
)


def upgrade() -> None:
    """Apply this revision."""
    op.create_table(
        "audit_log",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("occurred_at", TIMESTAMP, server_default=sa.text("now()"), nullable=False),
        sa.Column("action", AUDIT_ACTION, nullable=False),
        sa.Column("actor_person_id", sa.Uuid(), nullable=False),
        sa.Column("subject_user_id", sa.Uuid(), nullable=False),
        sa.Column("case_id", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(
            ["actor_person_id"],
            ["person.id"],
            name=op.f("fk_audit_log_actor_person_id_person"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["subject_user_id"],
            ["user.id"],
            name=op.f("fk_audit_log_subject_user_id_user"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_log")),
    )
    op.create_index(
        op.f("ix_audit_log_actor_person_id"), "audit_log", ["actor_person_id"], unique=False
    )
    op.create_index(
        op.f("ix_audit_log_subject_user_id"), "audit_log", ["subject_user_id"], unique=False
    )

    for script in SCRIPTS:
        op.execute(read_sql(script))


def downgrade() -> None:
    """Undo this revision."""
    for statement in DROP_OBJECTS:
        op.execute(statement)

    op.drop_index(op.f("ix_audit_log_subject_user_id"), table_name="audit_log")
    op.drop_index(op.f("ix_audit_log_actor_person_id"), table_name="audit_log")
    op.drop_table("audit_log")
    AUDIT_ACTION.drop(op.get_bind())
