"""authorization chokepoint reads and the supervision rank rule

Revision ID: 9a71c4be0d3f
Revises: 446183e8cc5f
Create Date: 2026-08-17 10:41:07.912004

E0-11: the three read views `backend/app/services/authz.py` resolves a purview
over, the grants that let the application connection read them, and the role-rank
rule on supervision edges that E0-09 measured missing and left for this ticket
(SPEC §2.1, §4.1 invariant 2; ADR 0027, ADR 0041, ADR 0044, ADR 0046).

Nothing here is autogenerated. This revision creates no table and alters no
column, so `alembic check` compares none of it in either direction — it reads
neither `pg_class` for views, nor ACLs, nor `pg_proc`, which E0-10 measured and
E0-20 item 3b records. The tests in
`tests/integration/test_supervision_edges_run_up_the_role_ranks.py`,
`tests/integration/test_own_grant_follows_the_role_grain.py` and
`tests/integration/test_a_scoped_reader_refuses_what_is_outside_the_purview.py`
are the only thing that notices, and the last two run over a `pulse_app`
connection precisely so that a missing grant fails as a test rather than as a
production incident.

**The read views exist because the chokepoint could not answer anything without
them.** E0-10 left `pulse_app` holding `SELECT` on `public.section_roster` and
`public.section_enrollment_count` and on nothing else, so a resolver asked
"which assignments does this person hold" was refused by the server. The three
views are the minimum that answers SPEC §2.1's own-grant question: an assignment
with its scope and its edge, which courses a person leads, and the containment
chain above every org node. ADR 0046 records why a purview is a set of nodes
materialised per level rather than a predicate.

**The rank rule extends E0-09's trigger rather than adding a second one.** ADR
0027 gives the argument for one row-level trigger over one table, and ADR 0044
gives the argument for this rule living there rather than in the resolver: the
resolver is not the only writer — E0-17's seed script, E9's CSV import and §6.3's
People editor all reach `role_assignment` — and a rule enforced by whoever
happens to read the graph is not enforced.

**The downgrade puts E0-09's function body back verbatim rather than dropping the
trigger.** `PREVIOUS_SUPERVISION_EDGE_TRIGGER_FUNCTION` below is the text of
revision `014ccb3d0fe5`, character for character, with `CREATE FUNCTION` changed
to `CREATE OR REPLACE FUNCTION` so that the trigger attached to it survives the
replacement. Dropping the trigger instead would leave a downgraded database
accepting reporting cycles and edges into Care assignments — rules this revision
never touched — which E0-10 shipped the wrong way round once and had to fix.
"""

from collections.abc import Sequence

from alembic import op

from app.views_sql import read_sql

# revision identifiers, used by Alembic.
revision: str = "9a71c4be0d3f"
down_revision: str | Sequence[str] | None = "446183e8cc5f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# The scripts this revision runs, in the order it runs them. The three views
# first, because the grants name them. Order is written out rather than globbed,
# for the reason E0-10's revision gives: a directory listing is not a dependency
# order, and a file added to the directory does nothing until a revision names
# it.
SCRIPTS = (
    "assignment_scope_v001",
    "lead_faculty_course_v001",
    "containment_path_v001",
    "authz_grants_v001",
)

# What the downgrade removes. Only the three views, and the grants go with them
# because a privilege cannot outlive the object it is on — `authz_grants_v001.sql`
# deliberately makes no grant on anything that survives, which is what leaves this
# list as short as it is. `USAGE ON SCHEMA public` is not revoked here for the
# same reason it is not granted here: E0-10's revision writes that ACL entry and
# its own downgrade is the only thing that can take it back.
DROP_OBJECTS = (
    "DROP VIEW IF EXISTS public.containment_path",
    "DROP VIEW IF EXISTS public.lead_faculty_course",
    "DROP VIEW IF EXISTS public.assignment_scope",
)

# E0-09's supervision-edge trigger with the role-rank rule added. Read this
# against revision `014ccb3d0fe5`, which carries the long note on the five
# details of the original that are load-bearing — the schema qualification, the
# `AFTER` timing, the `CYCLE` clause, the walk over assignment ids rather than
# `person_id`, and the advisory lock. All five are unchanged. What is new is
# below, and there are three parts to it.
#
# **The rank is the position of a role in SPEC §2.1's canonical chain**, held as
# one array so that the order exists in exactly one place. `array_position`
# answers `NULL` for a role that is not in the chain — `CARE` and `ADMIN` — and
# every comparison below treats that as a refusal rather than as a zero. That is
# the same fail-closed shape `SCOPE_GRAIN_RULE`'s `ELSE false` gives the scope
# rule, and for the same reason: a role added to the enum without a rank cannot
# be given an edge at all until somebody decides where it sits.
#
# **An edge is legal only where `rank(child) < rank(parent)`**, which is the rule
# E0-09 left measured and unenforced. Its two named failures are an equal-rank
# edge — `LEAD_FACULTY -> LEAD_FACULTY`, which puts one lead's courses inside a
# sibling lead's purview and is SPEC §4.1 invariant 2 written as a row — and an
# inversion such as `VP_ACADEMICS -> CHAIR`, which puts the whole institution
# inside a chair's. Neither row is wrong on its face and neither errors.
#
# **The rank is read off the two assignments and never off the person holding
# them.** §2.1 attaches the edge to the assignment — "`reportsTo` edges connect
# role assignments, not people or org nodes" — and calls two-hat people ordinary:
# a lead who also teaches a section of somebody else's course holds an
# `INSTRUCTOR` assignment whose edge to that course's lead is legal. A rule
# written over `person_id` refuses that and passes every refusal test there is,
# which is the trap ADR 0027 already records for the cycle walk.
#
# **The rank check runs before the cycle walk, and that changes which rule
# answers for a cycle.** Every cycle contains at least one edge that does not
# increase in rank, so the rank rule refuses the closing edge of every cycle this
# schema can now express, and E0-09's cycle guard is reached only where the rank
# rule has already passed. Both are kept: the cycle walk is what still holds if a
# later ticket changes the rank order, adds a role, or replaces this rule, and
# `docs/MISTAKES.md` entry 3 is explicit that where two rules can refuse the same
# row, the behavioural test cannot say which one did. ADR 0044 carries the
# consequence in full, including the depth bound the rank order imposes.
#
# **The mirror of the edge rule, on the row at the top of the edge.** An edge can
# also be made illegal by changing the *parent's* role — an administrator editing
# a chair into a lead faculty member in §6.3's People editor leaves whatever
# reported to that chair reporting to a lead. E0-09's Care rule already closes the
# same shape for the same reason (a row that "may not become a CARE assignment
# while other assignments report to it"), and closing it for one rule and not the
# other is `docs/MISTAKES.md` entry 13 exactly. It runs only on an `UPDATE` that
# changes the role: no row can have children at the moment it is inserted, so an
# ordinary insert pays nothing for it, and the advisory lock is taken on that
# narrow condition rather than on every write.
#
# It sits after E0-09's Care rule so that a chair with children turned into a
# `CARE` assignment is still refused by the rule named for it, with the message
# that names it, rather than by the rank rule underneath.
SUPERVISION_EDGE_TRIGGER_FUNCTION = """
CREATE OR REPLACE FUNCTION public.role_assignment_refuse_illegal_supervision_edge() RETURNS trigger
LANGUAGE plpgsql
SET search_path = pg_catalog, public, pg_temp
AS $$
DECLARE
    supervision_chain constant public.assignment_role[] := ARRAY[
        'INSTRUCTOR',
        'LEAD_FACULTY',
        'CHAIR',
        'ASSISTANT_DEAN',
        'DEAN',
        'VP_ACADEMICS'
    ]::public.assignment_role[];
    role_changed boolean;
    parent_role public.assignment_role;
    child_rank integer;
    parent_rank integer;
    closes_a_cycle boolean;
BEGIN
    role_changed := TG_OP = 'UPDATE' AND OLD.role IS DISTINCT FROM NEW.role;

    IF NEW.reports_to IS NOT NULL OR NEW.role = 'CARE' OR role_changed THEN
        IF current_setting('transaction_isolation') = 'repeatable read' THEN
            RAISE EXCEPTION
                'role assignment % carries a supervision edge, the CARE role or a changed role, '
                'and this transaction is REPEATABLE READ. The guards that refuse reporting '
                'cycles and illegal supervision edges read the rest of the graph, and at this '
                'isolation level that read uses a snapshot taken before any concurrent edge was '
                'committed, so a cycle written by two transactions at once would be stored. Use '
                'READ COMMITTED or SERIALIZABLE.',
                NEW.id
                USING ERRCODE = 'check_violation';
        END IF;
        PERFORM pg_advisory_xact_lock('public.role_assignment'::regclass::oid::bigint);
    END IF;

    IF NEW.reports_to IS NOT NULL THEN
        SELECT above.role INTO parent_role
          FROM public.role_assignment AS above
         WHERE above.id = NEW.reports_to;

        IF parent_role = 'CARE' THEN
            RAISE EXCEPTION
                'role assignment % may not report to %: a CARE assignment is never the '
                'target of a reporting edge, because it supervises nothing (SPEC 2.1)',
                NEW.id, NEW.reports_to
                USING ERRCODE = 'check_violation';
        END IF;

        child_rank := array_position(supervision_chain, NEW.role);
        parent_rank := array_position(supervision_chain, parent_role);

        IF child_rank IS NULL OR parent_rank IS NULL OR child_rank >= parent_rank THEN
            RAISE EXCEPTION
                'role assignment % in role % may not report to % in role %: a supervision edge '
                'runs from a role to one that outranks it in the chain INSTRUCTOR, LEAD_FACULTY, '
                'CHAIR, ASSISTANT_DEAN, DEAN, VP_ACADEMICS (SPEC 2.1), and a role outside that '
                'chain holds no rank to compare',
                NEW.id, NEW.role, NEW.reports_to, parent_role
                USING ERRCODE = 'check_violation';
        END IF;

        WITH RECURSIVE ancestor (assignment_id) AS (
                SELECT NEW.reports_to
            UNION ALL
                SELECT above.reports_to
                  FROM public.role_assignment AS above
                  JOIN ancestor ON above.id = ancestor.assignment_id
                 WHERE above.reports_to IS NOT NULL
        ) CYCLE assignment_id SET already_walked USING walked
        SELECT EXISTS (SELECT 1 FROM ancestor WHERE ancestor.assignment_id = NEW.id)
          INTO closes_a_cycle;

        IF closes_a_cycle THEN
            RAISE EXCEPTION
                'role assignment % may not report to %: the edge closes a reporting cycle '
                'in the supervision graph',
                NEW.id, NEW.reports_to
                USING ERRCODE = 'check_violation';
        END IF;
    END IF;

    IF NEW.role = 'CARE' AND EXISTS (
        SELECT 1 FROM public.role_assignment AS below WHERE below.reports_to = NEW.id
    ) THEN
        RAISE EXCEPTION
            'role assignment % may not become a CARE assignment while other assignments '
            'report to it: a CARE assignment sits outside the supervision graph (SPEC 2.1)',
            NEW.id
            USING ERRCODE = 'check_violation';
    END IF;

    IF role_changed AND EXISTS (
        SELECT 1
          FROM public.role_assignment AS below
         WHERE below.reports_to = NEW.id
           AND (
                   array_position(supervision_chain, below.role) IS NULL
                OR array_position(supervision_chain, NEW.role) IS NULL
                OR array_position(supervision_chain, below.role)
                   >= array_position(supervision_chain, NEW.role)
           )
    ) THEN
        RAISE EXCEPTION
            'role assignment % may not change to role %: an assignment already reporting to it '
            'holds a role that the new one does not outrank in the chain INSTRUCTOR, '
            'LEAD_FACULTY, CHAIR, ASSISTANT_DEAN, DEAN, VP_ACADEMICS (SPEC 2.1). Re-point what '
            'reports to it first.',
            NEW.id, NEW.role
            USING ERRCODE = 'check_violation';
    END IF;

    RETURN NULL;
END;
$$
"""

# Revision `014ccb3d0fe5`'s function, character for character, with
# `CREATE FUNCTION` changed to `CREATE OR REPLACE FUNCTION`. Written out here
# rather than imported or read back out of `pg_proc`, for the reason every
# revision in this tree gives for writing its DDL out: a migration records what
# was applied on the day it ran, and a downgrade that reinstates whatever the
# database happens to hold reinstates nothing.
PREVIOUS_SUPERVISION_EDGE_TRIGGER_FUNCTION = """
CREATE OR REPLACE FUNCTION public.role_assignment_refuse_illegal_supervision_edge() RETURNS trigger
LANGUAGE plpgsql
SET search_path = pg_catalog, public, pg_temp
AS $$
DECLARE
    closes_a_cycle boolean;
BEGIN
    IF NEW.reports_to IS NOT NULL OR NEW.role = 'CARE' THEN
        IF current_setting('transaction_isolation') = 'repeatable read' THEN
            RAISE EXCEPTION
                'role assignment % carries a supervision edge or the CARE role, and this '
                'transaction is REPEATABLE READ. The guard that refuses reporting cycles reads '
                'the rest of the graph, and at this isolation level that read uses a snapshot '
                'taken before any concurrent edge was committed, so a cycle written by two '
                'transactions at once would be stored. Use READ COMMITTED or SERIALIZABLE.',
                NEW.id
                USING ERRCODE = 'check_violation';
        END IF;
        PERFORM pg_advisory_xact_lock('public.role_assignment'::regclass::oid::bigint);
    END IF;

    IF NEW.reports_to IS NOT NULL THEN
        IF (
            SELECT above.role FROM public.role_assignment AS above WHERE above.id = NEW.reports_to
        ) = 'CARE' THEN
            RAISE EXCEPTION
                'role assignment % may not report to %: a CARE assignment is never the '
                'target of a reporting edge, because it supervises nothing (SPEC 2.1)',
                NEW.id, NEW.reports_to
                USING ERRCODE = 'check_violation';
        END IF;

        WITH RECURSIVE ancestor (assignment_id) AS (
                SELECT NEW.reports_to
            UNION ALL
                SELECT above.reports_to
                  FROM public.role_assignment AS above
                  JOIN ancestor ON above.id = ancestor.assignment_id
                 WHERE above.reports_to IS NOT NULL
        ) CYCLE assignment_id SET already_walked USING walked
        SELECT EXISTS (SELECT 1 FROM ancestor WHERE ancestor.assignment_id = NEW.id)
          INTO closes_a_cycle;

        IF closes_a_cycle THEN
            RAISE EXCEPTION
                'role assignment % may not report to %: the edge closes a reporting cycle '
                'in the supervision graph',
                NEW.id, NEW.reports_to
                USING ERRCODE = 'check_violation';
        END IF;
    END IF;

    IF NEW.role = 'CARE' AND EXISTS (
        SELECT 1 FROM public.role_assignment AS below WHERE below.reports_to = NEW.id
    ) THEN
        RAISE EXCEPTION
            'role assignment % may not become a CARE assignment while other assignments '
            'report to it: a CARE assignment sits outside the supervision graph (SPEC 2.1)',
            NEW.id
            USING ERRCODE = 'check_violation';
    END IF;

    RETURN NULL;
END;
$$
"""


def upgrade() -> None:
    """Apply this revision."""
    for script in SCRIPTS:
        op.execute(read_sql(script))
    op.execute(SUPERVISION_EDGE_TRIGGER_FUNCTION)


def downgrade() -> None:
    """Undo this revision."""
    op.execute(PREVIOUS_SUPERVISION_EDGE_TRIGGER_FUNCTION)
    for statement in DROP_OBJECTS:
        op.execute(statement)
