"""identity schema and lti registration tables

Revision ID: c8dd2256b20d
Revises: 216896354431
Create Date: 2026-08-16 06:54:46.657499

The six tables of SPEC §8 that say who someone is — user, user_identity, person,
enrollment (E0-08's `app.models.identity`) — and the registration they hang off,
lti_platform and lti_deployment (`app.models.lti`).

Autogenerated from those two modules and then changed in three ways, each noted
where it appears:

  - `btree_gist` is created before `enrollment`, because the exclusion constraint
    on that table compares two `uuid` columns with `=` and the GiST access method
    has no operator class for `uuid` without it;
  - `jwks_fetched_at` is written as `sa.DateTime(timezone=True)` rather than as
    the model's own `AwareDateTime`, which autogenerate renders as an
    unimportable name — the same edit E0-06's revision made, for the same reason
    given there;
  - the rest is reformatting, to match the revisions E0-05 and E0-06 wrote.

**The exclusion constraint is rendered here and is not compared afterwards.**
Autogenerate emits it inside `op.create_table` because it is on the model's
`Table`, which is worth knowing precisely so that it is not mistaken for
coverage: the constraint is invisible to `alembic check` in both directions.
Alembic's own Postgres implementation drops the backing GiST index from the
reflected index set (`correct_for_autogen_constraints`), and nothing compares
`pg_constraint` rows of type `x`. Change the rule in `app/models/identity.py`
without writing a migration and the check stays green.
`tests/integration/test_identity_schema.py` asserts the behaviour against a real
server, which is the only thing that can. ADR 0021 records the decision and the
measurement.

The check constraint below is half-covered, which is worth knowing separately.
E0-07 found that `alembic check` does not compare `CheckConstraint` expressions;
on the pinned Alembic 1.19 a `checkconstraint_byname` plugin now compares the
*name*, so renaming the constraint in the model is caught and changing its
expression still is not. Both were measured against this schema on the pinned
Postgres.

Every constraint name except the exclusion constraint's comes from `op.f(...)`,
which is the naming convention on `Base.metadata` rendering it. The exclusion
constraint is named by hand because SQLAlchemy's naming convention has a template
per constraint kind and no kind matches this one — see `app/models/base.py`.
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "c8dd2256b20d"
down_revision: str | Sequence[str] | None = "216896354431"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# `jwks_fetched_at` is declared in the model as `AwareDateTime`, a
# `TypeDecorator` that refuses a naive value at the bind boundary (ADR 0019).
# That guard is a property of the application's write path and not of the schema:
# the DDL it emits is exactly this. Written out rather than imported for the
# reason E0-06's revision gives — a migration records what was applied on the day
# it ran, and importing an application class would make this revision change
# meaning whenever that class did. `alembic check` compares the compiled type, so
# the two stay in step.
TIMESTAMP = sa.DateTime(timezone=True)


def upgrade() -> None:
    """Apply this revision."""
    # Equality inside a GiST index needs an operator class per type, and core
    # Postgres ships none for `uuid`; `btree_gist` supplies them. Without it the
    # `CREATE TABLE` below fails with "data type uuid has no default operator
    # class for access method gist". Creating an extension needs a superuser,
    # which is the identity every migration already runs as (ADR 0009).
    op.execute("CREATE EXTENSION IF NOT EXISTS btree_gist")

    op.create_table(
        "lti_platform",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("issuer", sa.Text(), nullable=False),
        sa.Column("client_id", sa.Text(), nullable=False),
        sa.Column("jwks_url", sa.Text(), nullable=False),
        sa.Column("jwks_fetched_at", TIMESTAMP, nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_lti_platform")),
        sa.UniqueConstraint("issuer", "client_id", name=op.f("uq_lti_platform_issuer_client_id")),
    )
    op.create_table(
        "lti_deployment",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("lti_platform_id", sa.Uuid(), nullable=False),
        sa.Column("deployment_id", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["lti_platform_id"],
            ["lti_platform.id"],
            name=op.f("fk_lti_deployment_lti_platform_id_lti_platform"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_lti_deployment")),
        sa.UniqueConstraint(
            "lti_platform_id",
            "deployment_id",
            name=op.f("uq_lti_deployment_lti_platform_id_deployment_id"),
        ),
    )
    op.create_table(
        "user",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("lti_platform_id", sa.Uuid(), nullable=False),
        sa.Column("lms_user_id", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["lti_platform_id"],
            ["lti_platform.id"],
            name=op.f("fk_user_lti_platform_id_lti_platform"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user")),
        sa.UniqueConstraint(
            "lti_platform_id", "lms_user_id", name=op.f("uq_user_lti_platform_id_lms_user_id")
        ),
    )
    op.create_table(
        "person",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=True),
        sa.Column("identity_name", sa.Text(), nullable=False),
        sa.Column("category", sa.String(length=50), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"], ["user.id"], name=op.f("fk_person_user_id_user"), ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_person")),
        sa.UniqueConstraint("user_id", name=op.f("uq_person_user_id")),
    )
    op.create_table(
        "user_identity",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("identity_name", sa.Text(), nullable=False),
        sa.Column("identity_email", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"], ["user.id"], name=op.f("fk_user_identity_user_id_user"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_identity")),
        sa.UniqueConstraint("user_id", name=op.f("uq_user_identity_user_id")),
    )
    op.create_table(
        "enrollment",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("section_id", sa.Uuid(), nullable=False),
        sa.Column("started_on", sa.Date(), nullable=False),
        sa.Column("ended_on", sa.Date(), nullable=True),
        postgresql.ExcludeConstraint(
            (sa.column("user_id"), "="),
            (sa.column("section_id"), "="),
            (sa.text("daterange(started_on, ended_on, '[]')"), "&&"),
            using="gist",
            name="ex_enrollment_windows_do_not_overlap",
        ),
        sa.CheckConstraint(
            "ended_on IS NULL OR ended_on >= started_on",
            name=op.f("ck_enrollment_ends_on_or_after_it_starts"),
        ),
        sa.ForeignKeyConstraint(
            ["section_id"],
            ["section.id"],
            name=op.f("fk_enrollment_section_id_section"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["user.id"], name=op.f("fk_enrollment_user_id_user"), ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_enrollment")),
    )
    op.create_index(op.f("ix_enrollment_section_id"), "enrollment", ["section_id"], unique=False)


def downgrade() -> None:
    """Undo this revision."""
    op.drop_index(op.f("ix_enrollment_section_id"), table_name="enrollment")
    op.drop_table("enrollment")
    op.drop_table("user_identity")
    op.drop_table("person")
    op.drop_table("user")
    op.drop_table("lti_deployment")
    op.drop_table("lti_platform")
    # After `enrollment` is gone nothing depends on the extension, so this is a
    # true inverse rather than a courtesy. A later revision that wants
    # `btree_gist` creates it itself; it is downgraded before this one, so it
    # cannot be relying on this line still having run.
    op.execute("DROP EXTENSION IF EXISTS btree_gist")
