"""org containment schema

Revision ID: 8e376cdecc3b
Revises: 2f045e5e0336
Create Date: 2026-08-14 17:13:00.385560

The six containment tables of SPEC §2.1 — institution, college, department,
prefix, course, section (E0-05). Autogenerated from `app.models.org` and then
edited for two things only, both noted where they appear: the `course.level`
generation expression is spelled out rather than left as one escaped line, and
the downgrade drops the `course_level` enum type, which autogenerate does not
emit.

Every constraint name comes from `op.f(...)`, which is the naming convention on
`Base.metadata` rendering it. None is hand-written; see `app/models/base.py`.

**The generation expression below is a snapshot, not a reference.** It is
duplicated from `COURSE_LEVEL_DERIVATION` in `app/models/org.py` on purpose: a
migration records what was applied on the day it ran, so importing the model's
constant would make this revision change meaning whenever that constant did.
`alembic check` is what keeps the two in step going forward.
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8e376cdecc3b"
down_revision: str | Sequence[str] | None = "2f045e5e0336"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# SPEC §8's bands. The cast is on each arm rather than around the whole CASE
# because Postgres requires a generation expression to be immutable and a
# run-time text→enum conversion is only stable; the width test guards the
# integer cast, which is why a number that is not three or four digits derives
# NULL instead of raising; and the whole thing is spelled the way Postgres
# deparses it so that `alembic check` stays quiet while it matches.
# `app/models/org.py` carries the full reasoning.
COURSE_LEVEL_DERIVATION = """
CASE
    WHEN lms_number ~ '^[0-9]{3}$'::text THEN
        CASE
            WHEN lms_number::integer >= 0 AND lms_number::integer <= 99 THEN 'DEV'::course_level
            WHEN lms_number::integer >= 100 AND lms_number::integer <= 499 THEN 'UG'::course_level
            WHEN lms_number::integer >= 500 AND lms_number::integer <= 599 THEN 'UGGR'::course_level
            WHEN lms_number::integer >= 600 AND lms_number::integer <= 799 THEN 'GR'::course_level
            ELSE NULL::course_level
        END
    WHEN lms_number ~ '^[0-9]{4}$'::text THEN
        CASE
            WHEN lms_number::integer >= 8000 AND lms_number::integer <= 9999 THEN 'DR'::course_level
            ELSE NULL::course_level
        END
    ELSE NULL::course_level
END
"""

COURSE_LEVEL = sa.Enum("DEV", "UG", "UGGR", "GR", "DR", name="course_level")


def upgrade() -> None:
    """Apply this revision."""
    op.create_table(
        "institution",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_institution")),
        sa.UniqueConstraint("name", name=op.f("uq_institution_name")),
    )
    op.create_table(
        "college",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("institution_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.ForeignKeyConstraint(
            ["institution_id"],
            ["institution.id"],
            name=op.f("fk_college_institution_id_institution"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_college")),
        sa.UniqueConstraint("institution_id", "name", name=op.f("uq_college_institution_id_name")),
    )
    op.create_table(
        "department",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("college_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.ForeignKeyConstraint(
            ["college_id"],
            ["college.id"],
            name=op.f("fk_department_college_id_college"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_department")),
        sa.UniqueConstraint("college_id", "name", name=op.f("uq_department_college_id_name")),
    )
    op.create_table(
        "prefix",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("department_id", sa.Uuid(), nullable=False),
        sa.Column("code", sa.String(length=16), nullable=False),
        sa.ForeignKeyConstraint(
            ["department_id"],
            ["department.id"],
            name=op.f("fk_prefix_department_id_department"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_prefix")),
        sa.UniqueConstraint("code", name=op.f("uq_prefix_code")),
    )
    op.create_table(
        "course",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("prefix_id", sa.Uuid(), nullable=False),
        sa.Column("lms_number", sa.Text(), nullable=False),
        sa.Column("lms_title", sa.Text(), nullable=False),
        sa.Column(
            "level",
            COURSE_LEVEL,
            sa.Computed(COURSE_LEVEL_DERIVATION, persisted=True),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["prefix_id"],
            ["prefix.id"],
            name=op.f("fk_course_prefix_id_prefix"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_course")),
        sa.UniqueConstraint("prefix_id", "lms_number", name=op.f("uq_course_prefix_id_lms_number")),
    )
    op.create_table(
        "section",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("course_id", sa.Uuid(), nullable=False),
        sa.Column("lms_section_code", sa.String(length=16), nullable=False),
        sa.ForeignKeyConstraint(
            ["course_id"],
            ["course.id"],
            name=op.f("fk_section_course_id_course"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_section")),
    )


def downgrade() -> None:
    """Undo this revision."""
    op.drop_table("section")
    op.drop_table("course")
    op.drop_table("prefix")
    op.drop_table("department")
    op.drop_table("college")
    op.drop_table("institution")
    # Autogenerate does not emit this. `CREATE TYPE` rode in with `course`, so
    # without the matching drop the type outlives every table that used it and
    # the next upgrade fails with "type course_level already exists" — a
    # downgrade that cannot be undone.
    COURSE_LEVEL.drop(op.get_bind())
