"""a deployment holds one institution

Revision ID: a702938fcc97
Revises: b336333a2805
Create Date: 2026-08-20 22:45:00.345355

SPEC §8 says a deployment serves exactly one institution and requires that a
constraint hold it rather than an assumption. Until this revision nothing did:
a second `institution` row could be written, and the first thing to refuse it
was `uq_prefix_code` on that institution's `BIOL` — an error naming a
constraint, no institution, and the wrong row (ADR 0017, whose amendment records
the assumption becoming a rule).

**A unique index on a constant is the shape, because a check constraint cannot
count rows.** `(true)` is the same value in every row, so the second row
collides with the first and the error names this index. ADR 0072 records the
alternative measured and rejected — a `singleton boolean` column carrying
`UNIQUE` and `CHECK` — and the measurements behind the claim that `alembic
check` compares this index in both directions, expression included.

**On a database that already holds two institution rows this revision fails**,
and it should: there is no answer to which of them the deployment serves that a
migration can choose. No deployment has a second row today, so this is a note
for a reader of the traceback rather than a case to handle.

Autogenerated, then documented. The index name is spelled out rather than built
by `op.f(...)`: the `ix` template on `Base.metadata` interpolates a column name
and a textual expression has none to give it, so the model names this index
explicitly too, and the two spellings have to match.
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a702938fcc97"
down_revision: str | Sequence[str] | None = "b336333a2805"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply this revision."""
    op.create_index(
        "uq_institution_one_row", "institution", [sa.literal_column("(true)")], unique=True
    )


def downgrade() -> None:
    """Undo this revision."""
    op.drop_index("uq_institution_one_row", table_name="institution")
