"""term calendar schema

Revision ID: 216896354431
Revises: 0965af2a6623
Create Date: 2026-08-14 21:24:16.419552

The four calendar tables of SPEC §2.2 and §3.1 — term, week, start_letter_map,
survey_window (E0-06) — and the two changes to `section` that needed `term` to
exist first: its `term_id`, and the uniqueness rule over
`(course_id, term_id, lms_section_code)` that SPEC §8's "sections belong to
exactly one course and one term" rests on.

Autogenerated from `app.models.term` and then changed in two ways that alter
what it does, each noted where it appears: the timestamp columns are written as
`sa.DateTime(timezone=True)` rather than as the model's own type, and the two
`section` statements are reordered. The rest is reformatting, to match the
revision E0-05 wrote.

**`section.term_id` is added NOT NULL with no backfill**, which is correct only
because no deployment has section rows yet — sections arrive with the roster
sync in E1 and the seed script in E0-17, both later than this. There is no value
this revision could invent for an existing row: a section's term is a fact about
the world, not a default. If this ever has to run against a populated table, the
fix is a data migration that decides each row's term, not a nullable column.

Every constraint name comes from `op.f(...)`, which is the naming convention on
`Base.metadata` rendering it. None is hand-written; see `app/models/base.py`.
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "216896354431"
down_revision: str | Sequence[str] | None = "0965af2a6623"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# `opens_at` and `closes_at` are declared in the model as `AwareDateTime`, a
# `TypeDecorator` that refuses a naive value at the bind boundary. That guard is
# a property of the application's write path and not of the schema: the DDL it
# emits is exactly this, `timestamp with time zone`. Written out here rather than
# imported for the reason E0-05's revision gives for the course-level expression
# — a migration records what was applied on the day it ran, and importing an
# application class would make this revision change meaning whenever that class
# did. `alembic check` compares the compiled type, so the two stay in step.
TIMESTAMP = sa.DateTime(timezone=True)


def upgrade() -> None:
    """Apply this revision."""
    op.create_table(
        "term",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("institution_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("end_date", sa.Date(), nullable=False),
        sa.Column("length_weeks", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "end_date > start_date", name=op.f("ck_term_end_date_is_after_start_date")
        ),
        sa.CheckConstraint("length_weeks >= 1", name=op.f("ck_term_length_weeks_is_at_least_one")),
        sa.ForeignKeyConstraint(
            ["institution_id"],
            ["institution.id"],
            name=op.f("fk_term_institution_id_institution"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_term")),
        # Not redundant beside the primary key: a foreign key must reference a
        # unique constraint, and this is the one the two composite keys below
        # point at. Dropping it drops both cross-table length rules with it.
        sa.UniqueConstraint("id", "length_weeks", name=op.f("uq_term_id_length_weeks")),
        sa.UniqueConstraint("institution_id", "name", name=op.f("uq_term_institution_id_name")),
    )
    op.create_table(
        "start_letter_map",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("term_id", sa.Uuid(), nullable=False),
        sa.Column("term_length_weeks", sa.Integer(), nullable=False),
        sa.Column("letter", sa.String(length=1), nullable=False),
        sa.Column("length_weeks", sa.Integer(), nullable=False),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.CheckConstraint(
            "letter ~ '^[A-Z]$'", name=op.f("ck_start_letter_map_letter_is_one_upper_case_letter")
        ),
        # Local, and a comparison against this row's own term, because the
        # foreign key below is what makes `term_length_weeks` the term's length
        # rather than a number the row chose. ADR 0018.
        sa.CheckConstraint(
            "length_weeks >= 1 AND length_weeks <= term_length_weeks",
            name=op.f("ck_start_letter_map_length_weeks_fits_inside_the_term"),
        ),
        sa.ForeignKeyConstraint(
            ["term_id", "term_length_weeks"],
            ["term.id", "term.length_weeks"],
            name=op.f("fk_start_letter_map_term_id_term_length_weeks_term"),
            onupdate="CASCADE",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_start_letter_map")),
        sa.UniqueConstraint("term_id", "letter", name=op.f("uq_start_letter_map_term_id_letter")),
    )
    op.create_table(
        "week",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("term_id", sa.Uuid(), nullable=False),
        sa.Column("term_length_weeks", sa.Integer(), nullable=False),
        sa.Column("number", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "number >= 1 AND number <= term_length_weeks",
            name=op.f("ck_week_number_is_inside_the_term"),
        ),
        sa.ForeignKeyConstraint(
            ["term_id", "term_length_weeks"],
            ["term.id", "term.length_weeks"],
            name=op.f("fk_week_term_id_term_length_weeks_term"),
            onupdate="CASCADE",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_week")),
        sa.UniqueConstraint("term_id", "number", name=op.f("uq_week_term_id_number")),
    )
    op.create_table(
        "survey_window",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("section_id", sa.Uuid(), nullable=False),
        sa.Column("week_id", sa.Uuid(), nullable=False),
        sa.Column("opens_at", TIMESTAMP, nullable=False),
        sa.Column("closes_at", TIMESTAMP, nullable=False),
        sa.CheckConstraint(
            "closes_at > opens_at", name=op.f("ck_survey_window_closes_after_it_opens")
        ),
        sa.ForeignKeyConstraint(
            ["section_id"],
            ["section.id"],
            name=op.f("fk_survey_window_section_id_section"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["week_id"],
            ["week.id"],
            name=op.f("fk_survey_window_week_id_week"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_survey_window")),
        sa.UniqueConstraint(
            "section_id", "week_id", name=op.f("uq_survey_window_section_id_week_id")
        ),
    )
    op.create_index(op.f("ix_survey_window_week_id"), "survey_window", ["week_id"], unique=False)

    # See the module docstring on why this is NOT NULL with no backfill.
    op.add_column("section", sa.Column("term_id", sa.Uuid(), nullable=False))
    op.create_foreign_key(
        op.f("fk_section_term_id_term"), "section", "term", ["term_id"], ["id"], ondelete="RESTRICT"
    )
    # Reordered from what autogenerate emitted, which dropped the index first.
    # The unique constraint leads with `course_id`, so its index serves the
    # lookup by course that `ix_section_course_id` was added for — and creating
    # it before the drop means there is no point in this migration where that
    # lookup has no index. E0-06's scope makes the drop conditional on exactly
    # that column order.
    op.create_unique_constraint(
        op.f("uq_section_course_id_term_id_lms_section_code"),
        "section",
        ["course_id", "term_id", "lms_section_code"],
    )
    op.drop_index(op.f("ix_section_course_id"), table_name="section")


def downgrade() -> None:
    """Undo this revision."""
    op.create_index(op.f("ix_section_course_id"), "section", ["course_id"], unique=False)
    op.drop_constraint(
        op.f("uq_section_course_id_term_id_lms_section_code"), "section", type_="unique"
    )
    op.drop_constraint(op.f("fk_section_term_id_term"), "section", type_="foreignkey")
    op.drop_column("section", "term_id")
    op.drop_index(op.f("ix_survey_window_week_id"), table_name="survey_window")
    op.drop_table("survey_window")
    op.drop_table("week")
    op.drop_table("start_letter_map")
    op.drop_table("term")
