"""index the two uncovered containment foreign keys

Revision ID: 0965af2a6623
Revises: 8e376cdecc3b
Create Date: 2026-08-14 18:10:31.173199

`prefix.department_id` and `section.course_id`, from the review of E0-05.
Postgres indexes a primary key and a unique constraint and nothing else, so a
foreign key is unindexed unless something says otherwise, and both of these are
walked by parent: E0-09 computes purview by descending the containment tree, and
`section` is the leaf table that grows by a row per section per term. Unindexed
that is a sequential scan per parent — invisible on seed data, worse every term.

**Three other containment foreign keys deliberately get nothing here.**
`college.institution_id`, `department.college_id` and `course.prefix_id` each
lead a composite unique constraint (`uq_college_institution_id_name`,
`uq_department_college_id_name`, `uq_course_prefix_id_lms_number`), and a B-tree
on `(a, b)` serves a lookup on `a`. A second index would be written on every
insert and read by nothing.

Autogenerated. Index names come from the naming convention on `Base.metadata`
through `op.f(...)`, not from this file.
"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0965af2a6623"
down_revision: str | Sequence[str] | None = "8e376cdecc3b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply this revision."""
    op.create_index(op.f("ix_prefix_department_id"), "prefix", ["department_id"], unique=False)
    op.create_index(op.f("ix_section_course_id"), "section", ["course_id"], unique=False)


def downgrade() -> None:
    """Undo this revision."""
    op.drop_index(op.f("ix_section_course_id"), table_name="section")
    op.drop_index(op.f("ix_prefix_department_id"), table_name="prefix")
