"""role assignments and the supervision graph

Revision ID: 014ccb3d0fe5
Revises: c8dd2256b20d
Create Date: 2026-08-16 15:03:32.446863

The two tables SPEC §8 lists for §2.1's supervision graph — role_assignment and
lead_faculty_mapping (E0-09's `app.models.identity`) — and the `assignment_role`
enum type they need.

Autogenerated from that module and then changed in three ways:

  - the downgrade drops the `assignment_role` enum type, which autogenerate does
    not emit — the same edit E0-05's revision made, for the reason given there;
  - the trigger below is added by hand, because a trigger is invisible to
    autogenerate in both directions;
  - the rest is reformatting, to match the revisions E0-05, E0-06 and E0-08
    wrote.

**The trigger is what enforces the two rules a single row cannot state.** A
`CHECK` constraint may not look at a second row, and both "nothing reports to a
Care assignment" and "no chain of `reports_to` edges returns to where it
started" are facts about a *pair* of rows or a walk over many. ADR 0027 records
why this is a trigger rather than a deferrable constraint trigger or a check in
`app/services/`, and what that costs.

**Nothing compares this trigger afterwards.** `alembic check` does not read
`pg_trigger` or `pg_proc`, so dropping either object leaves the check green and
leaves the supervision graph accepting loops. The behavioural tests in
`tests/integration/test_role_assignment_graph.py` and the generated properties in
`tests/integration/test_supervision_graph_properties.py` are the only thing that
notices, which is why the properties generate cycles of every length up to eight
and close each of them from every rotation.

The two generated columns *are* half-covered, and differently: Alembic cannot
alter a generated column, so its whole response to a changed expression is one
normalised string comparison and a `UserWarning` — no error and no non-zero exit.
Both expressions here are written in Postgres's own deparsed shape so that the
warning fires on real drift rather than on every run (ADR 0015 established the
practice for `course.level`; `app/models/identity.py` carries the note).

The check constraints are half-covered in the third way E0-08's revision
describes: on the pinned Alembic 1.19 the `checkconstraint_byname` plugin
compares the constraint *name*, so a rename in the model is caught and a changed
expression is not.

Every constraint name comes from `op.f(...)`, which is the naming convention on
`Base.metadata` rendering it. The trigger and its function are named by hand:
the convention has a template per constraint kind and neither of these is a
constraint.
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "014ccb3d0fe5"
down_revision: str | Sequence[str] | None = "c8dd2256b20d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# The enum type `role_assignment.role` is declared with. Written out rather than
# imported from `app.models.identity` for the reason E0-05's and E0-08's
# revisions both give: a migration records what was applied on the day it ran,
# and importing an application class would make this revision change meaning
# whenever that class did. Named here because the downgrade needs an object to
# call `.drop()` on — `op.drop_table` does not remove the type that rode in with
# the column.
ASSIGNMENT_ROLE = sa.Enum(
    "INSTRUCTOR",
    "LEAD_FACULTY",
    "CHAIR",
    "ASSISTANT_DEAN",
    "DEAN",
    "VP_ACADEMICS",
    "CARE",
    "ADMIN",
    name="assignment_role",
)

# SPEC §2.1's scope-attachment table and the two entry doors, exactly as
# `app/models/identity.py` declares them. See that module for why the scope rule
# ends in `ELSE false`, why each door is enumerated positively rather than
# written as a negation, and why both are spelled the way Postgres deparses
# them.
SCOPE_GRAIN_RULE = """
num_nonnulls(institution_id, college_id, department_id, course_id, section_id) = 1
AND CASE role
        WHEN 'INSTRUCTOR' THEN section_id IS NOT NULL
        WHEN 'LEAD_FACULTY' THEN course_id IS NOT NULL
        WHEN 'CHAIR' THEN department_id IS NOT NULL
        WHEN 'ASSISTANT_DEAN' THEN college_id IS NOT NULL
        WHEN 'DEAN' THEN college_id IS NOT NULL
        WHEN 'VP_ACADEMICS' THEN institution_id IS NOT NULL
        WHEN 'CARE' THEN institution_id IS NOT NULL
        WHEN 'ADMIN' THEN institution_id IS NOT NULL
        ELSE false
    END
"""

LAUNCH_DOOR_DERIVATION = """
role = ANY (ARRAY[
    'INSTRUCTOR'::assignment_role,
    'LEAD_FACULTY'::assignment_role,
    'CHAIR'::assignment_role,
    'ASSISTANT_DEAN'::assignment_role,
    'DEAN'::assignment_role,
    'VP_ACADEMICS'::assignment_role
])
"""

WEB_LOGIN_DOOR_DERIVATION = """
role = ANY (ARRAY[
    'LEAD_FACULTY'::assignment_role,
    'CHAIR'::assignment_role,
    'ASSISTANT_DEAN'::assignment_role,
    'DEAN'::assignment_role,
    'VP_ACADEMICS'::assignment_role,
    'CARE'::assignment_role,
    'ADMIN'::assignment_role
])
"""

# The two cross-row rules of SPEC §2.1's supervision graph, as one trigger
# function. Five details of it are load-bearing and none is obvious.
#
# **It is an `AFTER` trigger, and that is what catches the shortest cycle.**
# Postgres checks a row's foreign keys after the row exists, so
# `INSERT ... (id, reports_to) VALUES (x, x)` is a legal self-reference written
# in one statement — no second write to fire a `BEFORE UPDATE` guard, and nothing
# for a service that edits existing assignments to intercept. Firing after the
# row is in place means the walk below starts from a graph that already contains
# the edge under test, whether it arrived by insert or by update.
#
# **The `CYCLE` clause is what guarantees the walk terminates.** Postgres 14 and
# later stop a recursive CTE from revisiting a row it has already produced; the
# alternative — walking upwards until the parent is NULL — terminates only while
# the graph is already acyclic, which is precisely what is in question. So a row
# set that somehow contains a loop makes this raise, rather than hang the
# connection that found it.
#
# **The walk compares assignment ids and never `person_id`.** SPEC §2.1: "a
# chair's lead-faculty assignment may report to their own chair assignment —
# legal and expected", and "assignment-level cycles are invalid, person-level
# cycles are fine". A guard written over the person passes every cycle test there
# is and makes the commonest two-hat arrangement in the institution unwritable.
#
# **The advisory lock is what makes the guard hold between two writers, and
# without it the guard is measurably wrong.** Both rules are read-then-write: the
# trigger asks what the rest of the graph looks like and then lets a row stand.
# Two concurrent transactions each see a graph without the other's edge, so both
# are allowed and the committed result is a loop — measured against this schema
# on the pinned Postgres, with `A -> B` and `B -> A` both committing and both
# edges stored. Taking a transaction-scoped advisory lock first serialises the
# writes that can break the invariant, and the second transaction then blocks,
# sees the first one's committed edge, and is refused. Measured the same way.
#
# It is taken only where there is cross-row work to do — an edge to check, or a
# row becoming Care — so an ordinary assignment with no supervisor does not queue
# behind anything. The key is the table's own oid, which is stable within a
# database and needs no registry of hand-picked constants. The cost is that
# concurrent re-parenting writes serialise; these are administrator edits in the
# People editor (§6.3) and rows in a CSV import, so the contention is a handful
# of writes by one person at a time.
#
# **The lock serialises the writers; it does not give them a fresh snapshot, so
# REPEATABLE READ is refused outright.** The lock makes the second writer wait,
# but under REPEATABLE READ its snapshot was fixed at its first statement, so the
# walk still reads a graph without the first writer's edge and the cycle is
# stored anyway — measured, 3 attempts out of 3, at two and at three assignments.
# Rather than leave that as a footnote nothing enforces, a write that needs the
# cross-row checks is refused at this isolation level. READ COMMITTED (each
# statement re-snapshots) and SERIALIZABLE (SSI aborts one side) both hold, and
# both are measured. ADR 0027 carries the table and says what would lift the
# restriction.
#
# The messages name what the writer did, because the write this refuses is an
# administrator re-pointing somebody's reporting line in the People editor
# (§6.3): "you have created a reporting loop" is actionable and "duplicate key
# value violates unique constraint" is a bug report.
SUPERVISION_EDGE_TRIGGER_FUNCTION = """
CREATE FUNCTION role_assignment_refuse_illegal_supervision_edge() RETURNS trigger
LANGUAGE plpgsql AS $$
DECLARE
    closes_a_cycle boolean;
BEGIN
    IF NEW.reports_to IS NOT NULL OR NEW.role = 'CARE' THEN
        IF current_setting('transaction_isolation') = 'repeatable read' THEN
            RAISE EXCEPTION
                'role assignment % carries a supervision edge or the CARE role, and this '
                'transaction is REPEATABLE READ. The guard that refuses reporting cycles reads '
                'the rest of the graph, and at this isolation level that read uses a snapshot '
                'taken before any concurrent edge was committed, so a cycle written by two '
                'transactions at once would be stored. Use READ COMMITTED or SERIALIZABLE.',
                NEW.id
                USING ERRCODE = 'check_violation';
        END IF;
        PERFORM pg_advisory_xact_lock('role_assignment'::regclass::oid::bigint);
    END IF;

    IF NEW.reports_to IS NOT NULL THEN
        IF (
            SELECT above.role FROM role_assignment AS above WHERE above.id = NEW.reports_to
        ) = 'CARE' THEN
            RAISE EXCEPTION
                'role assignment % may not report to %: a CARE assignment is never the '
                'target of a reporting edge, because it supervises nothing (SPEC 2.1)',
                NEW.id, NEW.reports_to
                USING ERRCODE = 'check_violation';
        END IF;

        WITH RECURSIVE ancestor (assignment_id) AS (
                SELECT NEW.reports_to
            UNION ALL
                SELECT above.reports_to
                  FROM role_assignment AS above
                  JOIN ancestor ON above.id = ancestor.assignment_id
                 WHERE above.reports_to IS NOT NULL
        ) CYCLE assignment_id SET already_walked USING walked
        SELECT EXISTS (SELECT 1 FROM ancestor WHERE ancestor.assignment_id = NEW.id)
          INTO closes_a_cycle;

        IF closes_a_cycle THEN
            RAISE EXCEPTION
                'role assignment % may not report to %: the edge closes a reporting cycle '
                'in the supervision graph',
                NEW.id, NEW.reports_to
                USING ERRCODE = 'check_violation';
        END IF;
    END IF;

    IF NEW.role = 'CARE' AND EXISTS (
        SELECT 1 FROM role_assignment AS below WHERE below.reports_to = NEW.id
    ) THEN
        RAISE EXCEPTION
            'role assignment % may not become a CARE assignment while other assignments '
            'report to it: a CARE assignment sits outside the supervision graph (SPEC 2.1)',
            NEW.id
            USING ERRCODE = 'check_violation';
    END IF;

    RETURN NULL;
END;
$$
"""

SUPERVISION_EDGE_TRIGGER = """
CREATE TRIGGER role_assignment_supervision_edge_is_legal
    AFTER INSERT OR UPDATE ON role_assignment
    FOR EACH ROW
    EXECUTE FUNCTION role_assignment_refuse_illegal_supervision_edge()
"""


def upgrade() -> None:
    """Apply this revision."""
    op.create_table(
        "lead_faculty_mapping",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("person_id", sa.Uuid(), nullable=False),
        sa.Column("course_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["course_id"],
            ["course.id"],
            name=op.f("fk_lead_faculty_mapping_course_id_course"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["person_id"],
            ["person.id"],
            name=op.f("fk_lead_faculty_mapping_person_id_person"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_lead_faculty_mapping")),
        sa.UniqueConstraint("course_id", name=op.f("uq_lead_faculty_mapping_course_id")),
    )
    op.create_index(
        op.f("ix_lead_faculty_mapping_person_id"),
        "lead_faculty_mapping",
        ["person_id"],
        unique=False,
    )
    op.create_table(
        "role_assignment",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("person_id", sa.Uuid(), nullable=False),
        sa.Column("role", ASSIGNMENT_ROLE, nullable=False),
        sa.Column("institution_id", sa.Uuid(), nullable=True),
        sa.Column("college_id", sa.Uuid(), nullable=True),
        sa.Column("department_id", sa.Uuid(), nullable=True),
        sa.Column("course_id", sa.Uuid(), nullable=True),
        sa.Column("section_id", sa.Uuid(), nullable=True),
        sa.Column("reports_to", sa.Uuid(), nullable=True),
        sa.Column(
            "permits_launch",
            sa.Boolean(),
            sa.Computed(LAUNCH_DOOR_DERIVATION, persisted=True),
            nullable=False,
        ),
        sa.Column(
            "permits_web_login",
            sa.Boolean(),
            sa.Computed(WEB_LOGIN_DOOR_DERIVATION, persisted=True),
            nullable=False,
        ),
        sa.CheckConstraint(
            SCOPE_GRAIN_RULE, name=op.f("ck_role_assignment_scope_node_matches_the_role")
        ),
        sa.CheckConstraint(
            "role <> 'CARE' OR reports_to IS NULL",
            name=op.f("ck_role_assignment_care_reports_to_nobody"),
        ),
        sa.ForeignKeyConstraint(
            ["college_id"],
            ["college.id"],
            name=op.f("fk_role_assignment_college_id_college"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["course_id"],
            ["course.id"],
            name=op.f("fk_role_assignment_course_id_course"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["department_id"],
            ["department.id"],
            name=op.f("fk_role_assignment_department_id_department"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["institution_id"],
            ["institution.id"],
            name=op.f("fk_role_assignment_institution_id_institution"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["person_id"],
            ["person.id"],
            name=op.f("fk_role_assignment_person_id_person"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["reports_to"],
            ["role_assignment.id"],
            name=op.f("fk_role_assignment_reports_to_role_assignment"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["section_id"],
            ["section.id"],
            name=op.f("fk_role_assignment_section_id_section"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_role_assignment")),
    )
    op.create_index(
        op.f("ix_role_assignment_person_id"), "role_assignment", ["person_id"], unique=False
    )
    op.create_index(
        op.f("ix_role_assignment_reports_to"), "role_assignment", ["reports_to"], unique=False
    )
    op.execute(SUPERVISION_EDGE_TRIGGER_FUNCTION)
    op.execute(SUPERVISION_EDGE_TRIGGER)


def downgrade() -> None:
    """Undo this revision."""
    # The trigger goes with the table; the function does not, so it is dropped
    # by name. Without this line the next upgrade fails with "function
    # role_assignment_refuse_illegal_supervision_edge already exists" — a
    # downgrade that cannot be undone.
    op.drop_index(op.f("ix_role_assignment_reports_to"), table_name="role_assignment")
    op.drop_index(op.f("ix_role_assignment_person_id"), table_name="role_assignment")
    op.drop_table("role_assignment")
    op.execute("DROP FUNCTION role_assignment_refuse_illegal_supervision_edge()")
    op.drop_index(op.f("ix_lead_faculty_mapping_person_id"), table_name="lead_faculty_mapping")
    op.drop_table("lead_faculty_mapping")
    # Autogenerate does not emit this either. `CREATE TYPE` rode in with
    # `role_assignment.role`, so without the matching drop the type outlives
    # every table that used it and the next upgrade fails with "type
    # assignment_role already exists".
    ASSIGNMENT_ROLE.drop(op.get_bind())
